<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AML Policy</name>
   <tag></tag>
   <elementGuidId>c59a1ce8-1ab0-43fb-96e3-54c96af35ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1892']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1892 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8a6b1bff-2be9-4608-85f2-6d720a8aead9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aml-policy/</value>
      <webElementGuid>493fa4a1-3c21-48c0-8e9b-791ac6abfec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AML Policy</value>
      <webElementGuid>3b574c31-0bfe-4b08-9094-ff3207fca4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1892&quot;)/a[1]</value>
      <webElementGuid>ecf48018-5462-4737-889c-795a7ffd649d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1892']/a</value>
      <webElementGuid>35790dc6-18c8-4a7c-8f69-66ebceda06d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AML Policy')]</value>
      <webElementGuid>8436cfcb-ede4-4c30-82c7-a8e5313cfaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[2]/following::a[1]</value>
      <webElementGuid>242cdfa0-bcfa-455a-a042-e165e3d0130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::a[2]</value>
      <webElementGuid>11d79e0e-4feb-4f82-8d44-8a45079c983e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>ead2b207-c3a8-4b04-95ad-3bcbaabf714c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crypto'])[1]/preceding::a[2]</value>
      <webElementGuid>ad45de12-7975-41a4-bb17-8f85828180c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AML Policy']/parent::*</value>
      <webElementGuid>03a4a356-7997-4483-9607-19c08460f8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/aml-policy/')]</value>
      <webElementGuid>f495bf49-2716-4836-8fb4-6c46ee655b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>4410ddd0-3b8b-4c02-a646-56171a3864be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aml-policy/' and (text() = 'AML Policy' or . = 'AML Policy')]</value>
      <webElementGuid>3098e60c-b810-4815-a17e-fed18dde9e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
