<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join us on Discord and follow us on socia_5edda7</name>
   <tag></tag>
   <elementGuidId>8b9edea2-035c-4dce-bf39-27a223c68185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-d56d2161']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.vce-icon-container.fab.fa-bitcoin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ccea4d2-459a-4da5-ba89-9eee7c72ae5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-container fab fa-bitcoin</value>
      <webElementGuid>fc13c62c-cf6e-442b-a361-bec94affb67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/MaxQuest_</value>
      <webElementGuid>91fb039d-7c78-4f72-b064-02bc7078523d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4f40826b-5717-4d93-a5be-67456158f1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>8ba4eb64-9b91-46c1-bb85-b90cbf84e64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-d56d2161&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]/a[@class=&quot;vce-icon-container fab fa-bitcoin&quot;]</value>
      <webElementGuid>95bba0b2-8f2c-4eb9-b5c8-b964d563113c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-d56d2161']/div/a</value>
      <webElementGuid>d8433e95-df90-4150-9912-df876ee97bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://twitter.com/MaxQuest_')]</value>
      <webElementGuid>6a9c894e-3777-400e-98c6-55ffc6762fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>4d2e13c2-5509-452a-81db-0957018cdaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://twitter.com/MaxQuest_']</value>
      <webElementGuid>ffd68d5b-2ad4-4368-b1e9-c9415043d745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
