<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join us on Discord and follow us on socia_5b2a32_1</name>
   <tag></tag>
   <elementGuidId>2798ed7f-232c-4274-a799-219c28151c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-4d4bc8a1']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-4d4bc8a1 > div.vce-features--icon.vce-icon > a.vce-icon-container.vcv-ui-icon-entypo.vcv-ui-icon-entypo-facebook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa4437f4-2e34-4f90-9c21-f045cb622c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook</value>
      <webElementGuid>c26773eb-b916-4e33-8c11-474093fb20d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.facebook.com/maxquestofficial/</value>
      <webElementGuid>49b133d9-3b48-4a31-84d6-10b97eefa75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ddf52023-9444-460f-aaf1-2c0cd1049cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>c0cb7374-f393-4881-8d06-a904d35ad50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-4d4bc8a1&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]/a[@class=&quot;vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook&quot;]</value>
      <webElementGuid>99da2ff1-005e-4b36-928d-d08ddd3cf13a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-4d4bc8a1']/div/a</value>
      <webElementGuid>331ff70b-ca6b-45c7-b0a4-41fc6445c207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.facebook.com/maxquestofficial/')]</value>
      <webElementGuid>02cdbf3d-b014-406d-8c2e-4590d6fdc8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>aeff287d-4541-476a-9005-04dca461f108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.facebook.com/maxquestofficial/']</value>
      <webElementGuid>0d240a4d-d38b-4d03-b364-9fe7875798da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
