<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join us on Discord and follow us on socia_5b2a32_1_2</name>
   <tag></tag>
   <elementGuidId>141f9205-95e0-4e66-a9ba-ddbad4816e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-a30233ea']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-a30233ea > div.vce-features--icon.vce-icon > a.vce-icon-container.vcv-ui-icon-entypo.vcv-ui-icon-entypo-facebook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92959e4b-05bb-425c-a463-7923534d9ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook</value>
      <webElementGuid>b24f0c5c-06ed-471f-921e-b6a85f96e666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.tiktok.com/@maxquestofficial</value>
      <webElementGuid>21cb1da7-b755-4d61-b21b-cd7cdda85ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>06b4b37c-5c87-4d2a-8a91-c414b56ffb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>af788cd0-0b1c-4f74-b293-f43deb6059e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-a30233ea&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]/a[@class=&quot;vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook&quot;]</value>
      <webElementGuid>1a140625-14d9-47f5-9cb6-f9fbc56810bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-a30233ea']/div/a</value>
      <webElementGuid>074882b1-9a6d-484b-b45d-a6625a033073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.tiktok.com/@maxquestofficial')]</value>
      <webElementGuid>0916e610-04af-4e15-9f1b-9ce2776681f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>8f6cc338-f8a3-4152-90c4-413f20a03512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.tiktok.com/@maxquestofficial']</value>
      <webElementGuid>44f074b0-fcbf-4b23-bd51-b79928671622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
