<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join us on Discord and follow us on socia_5b2a32</name>
   <tag></tag>
   <elementGuidId>c30c2906-af42-44bc-9266-53bdbf009d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-b3e68947']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.vce-icon-container.vcv-ui-icon-entypo.vcv-ui-icon-entypo-facebook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>901b26bb-6a47-4288-8dc4-b15d3c5c714e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook</value>
      <webElementGuid>ebe8e210-e3ba-4211-bfb5-3171c535990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://discord.gg/vv36AtBcBq</value>
      <webElementGuid>87fdbc85-7752-459a-bea3-d872cf49a3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7f518285-53ac-4c75-9510-b68c0bd2be77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>b50b3e46-3917-4b0c-b0ba-aa544aea27c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-b3e68947&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]/a[@class=&quot;vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-facebook&quot;]</value>
      <webElementGuid>8b0734fc-b471-4bad-ab3e-7b25d5bed4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-b3e68947']/div/a</value>
      <webElementGuid>2244cf0b-a2d2-4642-8437-ebfb2270c7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://discord.gg/vv36AtBcBq')]</value>
      <webElementGuid>10a1388d-d5d9-4f18-950d-4395b7cc4c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>58ee30f1-1c82-43d3-8800-92f15e338411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://discord.gg/vv36AtBcBq']</value>
      <webElementGuid>8f117583-7fb6-4169-a822-2e4b6d1c80ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
