<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Join us on Discord and follow us on socia_a92bb1</name>
   <tag></tag>
   <elementGuidId>cc20b09f-fd46-4e52-a477-48c7c2ef7561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-52a9faff']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.vce-icon-container.vcv-ui-icon-entypo.vcv-ui-icon-entypo-instagram</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89b10321-9dad-4185-9b0a-2bfa077111e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-instagram</value>
      <webElementGuid>bd91c3e7-d15e-445f-9194-b9c4f26824dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.instagram.com/maxquestofficial/</value>
      <webElementGuid>2157b616-13db-4bb8-ac52-6f9d02b95243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>214c19e8-f960-4647-95ee-f3648cba43f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>b3b3943d-478e-4e89-b5b9-e6183207ea67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-52a9faff&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]/a[@class=&quot;vce-icon-container vcv-ui-icon-entypo vcv-ui-icon-entypo-instagram&quot;]</value>
      <webElementGuid>835f0846-f6d9-4122-9e1e-7412769563e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-52a9faff']/div/a</value>
      <webElementGuid>6dfd56ca-3470-4d06-bb9f-5a700c65e182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.instagram.com/maxquestofficial/')]</value>
      <webElementGuid>2394b8e9-5654-4ba7-ab79-6eea54a3d71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>c2bac996-f5df-441f-9800-1757a9f3658b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.instagram.com/maxquestofficial/']</value>
      <webElementGuid>add49771-2d7c-440a-bc1f-1d63a41acd39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
