<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms  Conditions</name>
   <tag></tag>
   <elementGuidId>e7f4e022-bb90-4bc2-b908-967f977ee4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-131']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-131 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>acea1edd-08d6-41b3-97fb-2afda14b6181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/terms-conditions/</value>
      <webElementGuid>3ed4a4e2-034e-4208-820d-8260b29ac5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms &amp; Conditions</value>
      <webElementGuid>655a1d79-4440-4f4e-94aa-171943782e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-131&quot;)/a[1]</value>
      <webElementGuid>fd703507-0f93-4195-bdd6-f4043f8bb160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-131']/a</value>
      <webElementGuid>2b944508-ba4f-4341-a800-41c027394cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms &amp; Conditions')]</value>
      <webElementGuid>e069a8d2-451a-48a3-b928-f312562daa42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/following::a[1]</value>
      <webElementGuid>a640ff8b-bcb4-4261-a561-3bfedc85d54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/following::a[2]</value>
      <webElementGuid>6859931d-908c-4518-9a49-811806f5d3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>16954a52-e940-4f0e-a81e-cc0b1fcec89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>643212e0-4185-43c9-be87-80578672f116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/terms-conditions/')])[4]</value>
      <webElementGuid>22561839-47d4-413b-96ab-64ed23c66d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>32e3897d-5206-487d-b408-f878bca0978e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/terms-conditions/' and (text() = 'Terms &amp; Conditions' or . = 'Terms &amp; Conditions')]</value>
      <webElementGuid>fdc2ec3f-1246-48e2-b832-bf97c020aaec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
