<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jack Logan_slick-prev slick-arrow</name>
   <tag></tag>
   <elementGuidId>cf54a747-305d-4418-b4b4-8962775ff8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-695bec5c']/section/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-prev.slick-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6030ae7-01fa-4c4f-a757-ebf3e916ab3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-prev slick-arrow</value>
      <webElementGuid>048d22f6-8cce-4d04-98e8-762b8d16a45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-695bec5c&quot;)/section[@class=&quot;mobile-pillars&quot;]/div[@class=&quot;pillars-carousel slick-initialized slick-slider&quot;]/div[@class=&quot;slick-prev slick-arrow&quot;]</value>
      <webElementGuid>61e5ef0f-5d31-4b3b-9ff6-7ec863c1bbb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-695bec5c']/section/div/div</value>
      <webElementGuid>b22fad61-679f-481c-b385-07962e25a241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>7d211d2a-6d90-44d7-ab8d-15154fd3d611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
