<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Join us on Discord and follow us on soc_3cb19d</name>
   <tag></tag>
   <elementGuidId>5adaeae1-acec-42be-b37d-263581d03c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-79194f84']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vce-icon-group.vce-icon-group--gap-10.vce-icon-group-alignment--center.vce-icon-group-vertical-alignment--middle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>480ceeaa-e677-4133-826f-3236e8da84f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-icon-group vce-icon-group--gap-10 vce-icon-group-alignment--center vce-icon-group-vertical-alignment--middle</value>
      <webElementGuid>b99b0198-e0d1-4fa7-9562-7af6c9c84aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79194f84&quot;)/div[@class=&quot;vce-icon-group vce-icon-group--gap-10 vce-icon-group-alignment--center vce-icon-group-vertical-alignment--middle&quot;]</value>
      <webElementGuid>f4a65254-df0b-4ad4-9fc6-dc1401be5d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-79194f84']/div</value>
      <webElementGuid>b98abb2e-7ea6-4963-9b96-50a4c0ca904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join us on Discord and follow us on social media for sneak peaks, free stuff and much more!'])[1]/following::div[2]</value>
      <webElementGuid>e1718495-9488-4688-8ccb-abb52cd6199c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MaxQuest Community'])[1]/following::div[2]</value>
      <webElementGuid>a596a01e-3536-4fb2-881b-9896063178b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/preceding::div[19]</value>
      <webElementGuid>effbb69b-df69-45d7-ae39-1de29c6d13e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::div[19]</value>
      <webElementGuid>fbbd28d8-ed18-44c2-b7ff-ead19658a380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/div/div/div[2]/div[3]/div/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>b05c1455-8e8d-47bd-86d4-77320082cece</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
