<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Purchase with FIAT_vce-features--icon vce-icon</name>
   <tag></tag>
   <elementGuidId>e08acd66-4079-4331-ad4b-9dc766b10933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-1366de21']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vce-features--icon.vce-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>534b091e-923d-43eb-9da3-405dfcdf3973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-features--icon vce-icon</value>
      <webElementGuid>98a3f977-287d-4d72-8b07-0c0de2b3e880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-1366de21&quot;)/div[@class=&quot;vce-features--icon vce-icon&quot;]</value>
      <webElementGuid>9c351514-6ae1-4339-a1c7-ce91cd09a959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-1366de21']/div</value>
      <webElementGuid>f31fca6a-2601-4e61-8c5a-ae7bff30d3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase with FIAT'])[1]/following::div[12]</value>
      <webElementGuid>d8e92647-b124-4d13-9beb-d6efa15cb256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crypto Wallet'])[1]/following::div[32]</value>
      <webElementGuid>f9572266-11c9-4888-8d75-3513fbf67233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Heroes'])[1]/preceding::div[3]</value>
      <webElementGuid>509ffe98-5638-4a0f-b59b-eb30d9e178f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brock Ryder'])[1]/preceding::div[6]</value>
      <webElementGuid>eaa86329-0d06-471f-a53f-47ea0ed1e77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>8d1549ee-0ac5-4bec-8587-d79d0ee8750b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
