<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Purchase with FIAT_vce-yt-video-play_01e425</name>
   <tag></tag>
   <elementGuidId>4920c4d3-1e5a-4804-9e4b-7886f0cdabd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-6fea8f7c']/div/div[2]/div[2]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.vce-yt-video-player-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62f04ae2-7905-4376-9867-28c5b45ea0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-yt-video-player-iframe</value>
      <webElementGuid>e079f71d-f2c6-498e-a5ea-d4ff63262b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/vPC_7ZG5WMk?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1</value>
      <webElementGuid>21762a56-03c9-4286-9875-aaaf2e5cfe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6f48b14-cc59-44a6-90b8-d63d323ca16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cdc76728-eb2f-45d2-8ed8-6183d47238c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-6fea8f7c&quot;)/div[@class=&quot;vce-video-popup-wrapper vce-video-popup-wrapper-fullscreen&quot;]/div[@class=&quot;vce-video-popup-inner&quot;]/div[@class=&quot;vce-video-popup-video-block vce-video-popup-iframe-margin&quot;]/iframe[@class=&quot;vce-yt-video-player-iframe&quot;]</value>
      <webElementGuid>17f869d9-8fed-4cdd-b077-d5fa49707d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-6fea8f7c']/div/div[2]/div[2]/iframe</value>
      <webElementGuid>078cc421-2803-4487-a7ad-f5aa02f1fb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>a2cf8777-ce6d-431e-8392-3a3c61885c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.youtube.com/embed/vPC_7ZG5WMk?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1']</value>
      <webElementGuid>00546ab4-b2b9-4af1-aa26-2a6139f3c77b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
