<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue with Google</name>
   <tag></tag>
   <elementGuidId>19614b00-e53f-4878-a912-a87dae627c8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalRegister']/div/div/div[2]/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modalRegister > div.modal-dialog.modal-sm > div.modal-content > div.modal-body > div.external-login > a.google-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4de90a6-395e-421e-84f1-547c3ece875e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f82dbe76-0300-4d1f-8dd0-51ec05b076d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-login</value>
      <webElementGuid>f92e12bd-f38d-4c88-b093-3fdea1c39127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with Google</value>
      <webElementGuid>92bfdd44-060a-4551-b71a-68bea4b2dcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalRegister&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;external-login&quot;]/a[@class=&quot;google-login&quot;]</value>
      <webElementGuid>650ff3b7-13fc-4b94-b0d7-b4755612dc3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalRegister']/div/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>7f48e158-f604-4283-be4f-a71af3384f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Facebook'])[2]/following::a[1]</value>
      <webElementGuid>c39c4859-fefe-43b7-8945-3b71a619f302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[2]/following::a[2]</value>
      <webElementGuid>e8bf6be9-937b-43af-9582-67c99935d655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>bd11d10c-ddf1-494a-a95f-02c5f4897968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>c784c797-deb8-487f-917f-0c2099743be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Continue with Google' or . = 'Continue with Google')]</value>
      <webElementGuid>70ed9155-44dd-41bf-a9e8-c546fad41f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
