<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FASTFIRE</name>
   <tag></tag>
   <elementGuidId>fef456d8-9a80-4483-897f-8d94372039b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3580']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3580 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9dceac9c-ce8d-420f-bb08-eb0752d1a0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fastfire/</value>
      <webElementGuid>6663ec68-baa9-480b-8292-aed0db4d57b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fastfire</value>
      <webElementGuid>a65a7ef1-8b7d-412a-b72c-f2270dbcea8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3580&quot;)/a[1]</value>
      <webElementGuid>27c2d729-a622-4ab1-91ec-5bb2be4bfcf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e992fde-5c98-42fc-8e5a-d4238decefdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fastfire</value>
      <webElementGuid>2dd5850d-d936-4cad-a056-2f63b10afc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FASTFIRE</value>
      <webElementGuid>e77338ec-b7ea-45f8-b141-c50d196bc9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-resp&quot;)/div[@class=&quot;container&quot;]/ul[@class=&quot;navbar-resp&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>a2c0b437-b147-4195-9130-de5ba72b9799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3580']/a</value>
      <webElementGuid>da7a1d59-92ed-4835-a80a-ebb411615fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fastfire')]</value>
      <webElementGuid>6b8c2dbd-5776-44aa-8167-a067e9741515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Battleground'])[1]/following::a[1]</value>
      <webElementGuid>710d1f04-a159-43da-abc8-5205b1461d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[2]</value>
      <webElementGuid>ad447c79-5c71-47f3-b911-ecd7dc662612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triple Max Blast'])[1]/preceding::a[1]</value>
      <webElementGuid>1bd80871-26b2-4774-b6c8-c1989ccf7d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max Rewards'])[1]/preceding::a[2]</value>
      <webElementGuid>17960e43-a2cb-42b0-9d92-555526ae691d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fastfire']/parent::*</value>
      <webElementGuid>fed06ac4-ff29-401a-b2b1-58e627f67933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fastfire/')]</value>
      <webElementGuid>3f6f67b9-95d9-4607-b3bd-919ecf31f144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>3c6a047e-afd5-4a1a-8d0a-253357f86549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fastfire/' and (text() = 'Fastfire' or . = 'Fastfire')]</value>
      <webElementGuid>d6f8dc58-ca9c-42a7-a698-5dcbe198f152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar-resp']/div[2]/ul/li[2]/a</value>
      <webElementGuid>6d707439-54a0-4ab9-bfcc-218f8e8fe386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'FASTFIRE')])[2]</value>
      <webElementGuid>1fa3d07f-482a-4047-9f6a-bd9c4512218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATTLEGROUND'])[2]/following::a[1]</value>
      <webElementGuid>5438177c-c8c0-487b-b05a-904983e94366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::a[2]</value>
      <webElementGuid>d5969f73-8011-45ac-9538-452fb3874563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRIPLE MAX BLAST'])[2]/preceding::a[1]</value>
      <webElementGuid>3a57a4b6-cf0c-4663-be41-070028523cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAX REWARDS'])[2]/preceding::a[2]</value>
      <webElementGuid>fa125a66-1de6-4f94-a42c-42c1495e2c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/fastfire')])[2]</value>
      <webElementGuid>a9ab9149-6eb5-4187-8685-08f23791573a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fastfire' and (text() = 'FASTFIRE' or . = 'FASTFIRE')]</value>
      <webElementGuid>bd949fca-0a4b-4bdd-a08c-e07d6a3d537e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
