<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PLAY NOW</name>
   <tag></tag>
   <elementGuidId>4a1ff616-dd81-48a4-b94b-e7a12da6b103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.button.play-now</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1a29ae6-84ef-457c-a55e-1706481e979d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>1c3567b6-fd03-4397-92b5-d4897449f77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>5b5692cb-ddcf-478e-9195-bf8484d47d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>822c6853-59d5-41b7-8792-85aa3aa69ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>23193749-b44d-41eb-b6c9-d710e6ff328f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>509ca13c-6e22-4dc3-9464-f8960fc7e539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>d59fe19e-7ed3-4734-971c-248924f67cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>1f3ded0d-c1c4-4e6b-97e9-6d31af5bc2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>f177ceac-fc76-40c9-b66f-e0db6238e57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>bf7ea400-4e8c-4e45-982c-dcab9b8eb148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cf6665f-d564-4a9b-a737-3861a4a2c6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>62ba8410-2fdb-4fe4-bc84-df0132ad2b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>cd17c758-c360-4aca-a409-4edade86bf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>b717bf08-ba53-4b02-a99d-0eb3c2a1816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>8abcecce-0616-4f1f-8a1c-2b9e60062c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>459aef53-ebf1-4476-8c86-6b73a60552c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>4738735e-b804-40bd-8260-02fda215b564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/mission-amazon</value>
      <webElementGuid>65e86f6b-c2d0-418d-84b5-fd9d1f7e8ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>c682a144-967b-4074-aa69-ef0d82e1b6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>88cfb1ba-c647-459a-834d-db7522f07841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91dc53f8-b5a8-4f24-9446-2f3e9506bba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>91ae18cc-dc9c-446a-8240-aeec69bc0c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/mission-amazon</value>
      <webElementGuid>8ebac946-dbe9-4da3-ac3b-687bf96c4be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>51e16d42-4e87-4610-b93d-d0076f05c180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>890f66da-753d-40c3-8e3f-b3c9c70e9dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79b03bbc-467b-47ce-aa9f-96367c3b718e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>9bf8cca5-6a31-4740-a0c5-139430c89829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6a323907-6ffa-48e6-a02d-4cb8bf9edb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>51fca96c-d14c-419a-8615-6b49fafe6623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>6e66f957-cf63-48d3-a9b0-5379d3734bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4253f8a5-f336-465f-81bd-ddbbc1f0401c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>ff6ea863-60af-433d-a50e-a990f96db123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/mission-amazon</value>
      <webElementGuid>9e95693d-24da-4b57-8dc3-ca75d864a8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>9a490992-2659-4a04-abfa-d48ab89d06e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>6fcd5330-9b72-4143-945c-62d7b9f86659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af655834-97f6-40a2-bb55-335ef3d08a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>742d1fcc-0a5c-43de-8dee-a6f6daa6e1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>2e4012e5-2e40-4afc-8db4-fa25083a7658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>514b2332-cce1-4338-8cf4-857dd760b51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>f000f9fd-5a4e-4cfc-be37-03e367c4710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58454977-9129-4345-a495-2ce86e361368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>c6d5a9cb-a83b-405d-8664-fd947b3b100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>7bc1d365-d7ee-45e5-b5f0-e359b5b3f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>4866ed73-c9c6-4c52-8acf-98644bb49a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>c7a65679-1d65-4231-87c4-e9f42cef3d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>677a4bec-aeab-4548-9195-328796f72af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>544df035-4e45-4b95-b94a-948c795ebbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>3c3b921d-8bd9-4247-99a9-39dfbf68c170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>6b7700c4-3c32-4219-8594-b9042bfeb93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>2df6590f-47e9-42d1-9667-76ceb4bf382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e177d9f-5a7a-44f1-9516-e515feff3383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>bced5119-996b-4207-84e3-458c39f2b33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>81381cd4-dbdd-458c-91f2-d0599fe271d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>9daf03f9-bffc-4bdd-af36-97459a322d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>3e24598c-97fb-4378-8358-5406c3210680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c53b184d-43c4-4490-bfa5-44f424876992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>4613757b-a292-4cd6-ab41-2d359607d791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>7a05caa0-abdd-4243-8142-a8a9f4275eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>7e588eaa-0976-4c4e-b20f-44f8d34a92f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>11c1cd4f-9a98-46c4-9430-6001a080b102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e10e360e-6c07-4192-835e-c179c78eb82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>338297a0-f7ec-48f5-a0a6-853a726b440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>e833c293-8afc-42e6-865e-b741172e6744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>9a1225c0-db54-4169-a8e3-5d0bdff614e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>e3071cd1-360d-464b-a5ff-6bf81b13a62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f7bcd7b-35ee-4a5c-a760-a53050ddc74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>9ba86be6-0d08-4155-a415-a7f0b50bb1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/mission-amazon</value>
      <webElementGuid>3aa40123-55b2-4127-be10-64ca2c59c799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>9e5a51c8-29a7-40e3-94f9-c4a278436a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>ea6dcdf3-9b0b-4748-8185-03580bbfd522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41121a35-7ee2-43cd-8b19-092bab3d3e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>bcc69274-ff4e-48b6-b5b6-6375652e2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>476b8ecb-40be-4e6c-b9cc-78c78eea09d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>b0145848-ff2e-497e-92d6-5c126e98fe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>78d00679-bdd7-43ab-aae5-7ef4a2c5bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>768aaf5b-5b4a-492d-b60f-1f43baca1a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>b28f3c2b-b7cd-4164-992d-da772ba8a5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>bed01eab-7a5f-4cc1-af24-69f61e8fc312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>2a01f4df-4410-4d83-b973-0e4f97293ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>6f53bb8c-1a67-4304-b193-1c7c77f75553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f2ae40c-2e9a-478b-80ed-c0ccd77a6164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>7d481513-2af7-4f6b-bac5-d7640f3d8ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>76ca1c6c-c2b8-4115-b19c-0fc973c67b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>312a633f-20fe-4e42-bc9d-0ccd928d87a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>b351c311-13ac-4549-bb0b-25e39b0859ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a242c40b-c01f-408f-90ba-e5fc113d7bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button play-now</value>
      <webElementGuid>1e9a21d2-0873-4a33-b51d-8e7c7f154855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>b239a272-2c6c-4f1d-91c9-db50bd3b9c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play now</value>
      <webElementGuid>36bcae79-acf9-4545-b5ce-e9abae632849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/div[@class=&quot;room-buttons-overlay&quot;]/a[@class=&quot;btn button play-now&quot;]</value>
      <webElementGuid>d852a159-fa30-4e5a-9a2e-2b286dd92eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91af35e6-f4e6-4d11-b4c8-5f72b2908130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>b6437578-be00-4cc3-8f97-d9c4018d27b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>a1696b76-fc22-4f89-bc11-290381d18bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>93a50dce-2116-4538-8f1b-9a192f2580a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>f93b802b-7beb-46a7-8d56-fc92465dfb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bccedf06-014c-4468-9254-45421e6004b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-button</value>
      <webElementGuid>d27835e8-5723-432c-b302-a4d7632765bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/battleground/dragonstone</value>
      <webElementGuid>8197a989-b58e-4099-b603-4f2fd73337be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>5a63dea4-8e1d-402d-a09c-8bcd15554d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;mq-slider mq-animation anim-from-center&quot;]/div[@class=&quot;mq-slider-wrapper&quot;]/div[@class=&quot;mq-slider-container&quot;]/div[@class=&quot;mq-slider-item enable&quot;]/div[@class=&quot;mq-slider-overlay&quot;]/a[@class=&quot;slider-button&quot;]</value>
      <webElementGuid>6d9255e4-3d2c-4f2c-9196-a1e9d0fa0357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div/div[2]/a</value>
      <webElementGuid>c832951d-c523-4d2e-a5e2-a8e0ed711656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Play now')]</value>
      <webElementGuid>6193c049-de86-45d0-bc24-bf2657b8dc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHOOSE YOUR COIN PACK.'])[1]/following::a[1]</value>
      <webElementGuid>e7e561b5-1e8d-4d5a-932e-ce578a00c5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open private room'])[1]/preceding::a[1]</value>
      <webElementGuid>4bb8d4fc-ba07-4ce7-8ed8-7f176631d582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Play now']/parent::*</value>
      <webElementGuid>b86e676f-505b-4ca5-9c2a-c87cc08f3685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>3d8f8ef1-21e8-46cd-92d8-6440b20d4393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>282673c4-4d41-4b0a-9f53-41d292f848cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Play now' or . = 'Play now')]</value>
      <webElementGuid>4bbe13ef-5536-40c7-9b3f-2d3c5b207e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>b62b93f8-41fc-47ba-b56e-2f359b32eb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PLAY NOW')]</value>
      <webElementGuid>260d1a11-2082-44d8-b679-6f9a36cd4e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME HISTORY'])[2]/following::a[1]</value>
      <webElementGuid>36ded08b-bf45-43db-b0af-342500f48f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK TO HOME'])[2]/following::a[1]</value>
      <webElementGuid>83841f1b-58a3-4471-a8b8-cbe8f92c2a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAY NOW'])[2]/preceding::a[1]</value>
      <webElementGuid>49aa6ca8-738c-414c-803f-a086146ab03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMING SOON'])[1]/preceding::a[2]</value>
      <webElementGuid>122fe917-dc4a-4ce6-8f7e-123ba376a67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PLAY NOW']/parent::*</value>
      <webElementGuid>ed9701eb-7b19-4649-83f6-bab4418aa413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/battleground/dragonstone')]</value>
      <webElementGuid>bfcad05c-baa2-4cb1-b871-d7164334b784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>1f584875-6733-4fa2-80c2-bbe8d7aa2df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/battleground/dragonstone' and (text() = 'PLAY NOW' or . = 'PLAY NOW')]</value>
      <webElementGuid>54d8b198-3bda-4ef6-9335-44e6e58bb8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>cf91c42e-898e-4048-8750-8303df7f927d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'PLAY NOW')])[2]</value>
      <webElementGuid>2085c49e-3d48-4071-a82f-9a0ab2cc73af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAY NOW'])[1]/following::a[1]</value>
      <webElementGuid>8a4d4343-8f3c-4b47-a71a-53b3bafd7882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME HISTORY'])[2]/following::a[2]</value>
      <webElementGuid>75a922f0-5a2d-403a-926f-6973f3189bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMING SOON'])[1]/preceding::a[1]</value>
      <webElementGuid>47066537-def8-4ae4-8f16-ed075c3da93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMING SOON'])[2]/preceding::a[2]</value>
      <webElementGuid>8e8116e4-5561-4d81-9546-1a61309c4872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/battleground/mission-amazon')]</value>
      <webElementGuid>1c800f95-7a7b-470d-9a1f-33c882561eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>a8f299b1-fe46-467f-b799-2f0561fb610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/battleground/mission-amazon' and (text() = 'PLAY NOW' or . = 'PLAY NOW')]</value>
      <webElementGuid>50e40aa5-cf7c-434f-909c-2261b2ef715c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
