<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Game Max Quest. Version 1.0.17. Date 30.09.2022. FPS 143_app-screen</name>
   <tag></tag>
   <elementGuidId>30f52900-d339-4104-a93c-f8faccc1e3d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.app-layout-layer.app-layer-preloader > canvas.app-screen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>27d76a1d-d374-4a4d-9b2e-a5026acbf06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-screen</value>
      <webElementGuid>190efd5d-2192-488c-b0c0-522678fa6c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>48acff16-293d-41cb-b91c-e4594519e2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1130</value>
      <webElementGuid>742411fc-11b6-4c6b-8d2b-889e7550613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app-layout&quot;]/div[@class=&quot;app-layout-layer app-layer-preloader&quot;]/canvas[@class=&quot;app-screen&quot;]</value>
      <webElementGuid>8e83367b-a6d3-4f9e-905f-579519ac1733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Battleground  MaxQuest/iframe_HOW TO PLAY_app-game-frame</value>
      <webElementGuid>903ee464-131a-4652-a241-4939f7d49546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/canvas</value>
      <webElementGuid>93d534ae-d075-4b49-9d14-8a578dc47b9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
