<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>5926e7c9-80e3-45bb-93a0-f79a355b515f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.app-layout-layer.app-layer-preparepreloader > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a887be9-668a-4488-a4cf-5cf83fd0744d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app-layout&quot;]/div[@class=&quot;app-layout-layer app-layer-preparepreloader&quot;]/div[1]</value>
      <webElementGuid>a8980331-b6c5-46b2-8717-f65642b224ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Battleground  MaxQuest/iframe__gameUrlFrame</value>
      <webElementGuid>9a1110f6-2eb3-493c-bb0c-af3c3b1538b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>0dda1e5e-ea02-486a-ad82-9aaa63a9f6a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
