<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WINNER_vce-video-popup-close-button</name>
   <tag></tag>
   <elementGuidId>ba8014ed-1fde-4421-88fc-2622a7dc09a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-a7d1d684']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vce-video-popup-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6aa99ad-67d6-4c63-9b64-86cc51085584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-video-popup-close-button</value>
      <webElementGuid>a1474592-6259-472d-92d0-4dc10104b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-a7d1d684&quot;)/div[@class=&quot;vce-video-popup-wrapper vce-video-popup-wrapper-fullscreen&quot;]/div[@class=&quot;vce-video-popup-close-button&quot;]</value>
      <webElementGuid>c4b62dda-157a-4530-806c-a94764f0728d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-a7d1d684']/div/div</value>
      <webElementGuid>8c5c9076-db31-4ef1-ae79-f86751f9bf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e26797b5-a5a9-449f-8f52-9f0787e8b916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
