<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_WINNER_vce-yt-video-player-iframe</name>
   <tag></tag>
   <elementGuidId>6d80dfe2-25ed-4782-aea6-ebf3b6d7c4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-a7d1d684']/div/div[2]/div[2]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.vce-yt-video-player-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3f1c8073-bde2-48b3-8f36-41c8eb097784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-yt-video-player-iframe</value>
      <webElementGuid>21c85262-efd8-4310-a001-ceff510880c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/o8eoY4MB_3g?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1</value>
      <webElementGuid>dbc58c5e-e2e5-4b43-ab38-8499499ac933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b7d74f8-6867-42a0-b69c-ad5307e6c5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c6571068-e5da-49db-8730-e1dc96e19bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-a7d1d684&quot;)/div[@class=&quot;vce-video-popup-wrapper vce-video-popup-wrapper-fullscreen&quot;]/div[@class=&quot;vce-video-popup-inner&quot;]/div[@class=&quot;vce-video-popup-video-block vce-video-popup-iframe-margin&quot;]/iframe[@class=&quot;vce-yt-video-player-iframe&quot;]</value>
      <webElementGuid>d1ad1afa-71d7-4b38-be3b-607ac777ff12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-a7d1d684']/div/div[2]/div[2]/iframe</value>
      <webElementGuid>3f5827e0-8b10-46aa-89ff-3b45f57f023c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>1537c6dd-3caf-46b8-9638-dccc4fdbbe7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.youtube.com/embed/o8eoY4MB_3g?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1']</value>
      <webElementGuid>ff2f99e1-cfb5-4c88-9799-23880c513ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
