<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__gameUrlFrame</name>
   <tag></tag>
   <elementGuidId>9af31e83-3625-4421-a5b0-f2abd938f7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='gameUrlFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;gameUrlFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3b944e20-611e-43ce-bef2-c19fe9998103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/battleground/start?gameId=856&amp;buyIn=200000</value>
      <webElementGuid>b7a21216-8850-4ed4-a03e-ab3b15eecda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>5c4d563b-86a0-47a8-8f9c-7e06f3e2ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gameUrlFrame</value>
      <webElementGuid>fc5046d3-4d17-4798-8beb-8221b95fa610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-iframe</value>
      <webElementGuid>5906ce5a-5076-4a10-9006-704c01da66c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modalFixed&quot;]/div[@class=&quot;modal show&quot;]/div[@class=&quot;modal-container show&quot;]/iframe[@class=&quot;modal-iframe&quot;]</value>
      <webElementGuid>a81092a0-15cd-46a5-99a3-eda63ed45a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='gameUrlFrame']</value>
      <webElementGuid>a59e5cd3-074d-4d89-a01b-dcca8d683253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4f4e5ae8-3d1c-4a7e-98bb-feb6b66c0899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/battleground/start?gameId=856&amp;buyIn=200000' and @name = 'gameUrlFrame']</value>
      <webElementGuid>86b9614b-5653-4de3-b775-c8c6261b3620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
