<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>3517d27b-692a-4ab5-855d-1b4216526035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Room 1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d924dd11-dd9d-4c84-972d-2b7788bca6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>782b4bf9-778a-4f76-a2c4-4d5c3448f10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_MC.png</value>
      <webElementGuid>4e4a59e8-465e-4eb5-9681-ee64f2f86172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>871e5f0e-b6c6-48ae-b331-9c2356907c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>a91d35af-5ce9-4f2d-9aba-a4225ea4503d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>0716d935-1b24-409b-a49e-0a594ffbcd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>cd92b726-324b-45a8-b50e-b73a6fa289e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fa790f18-4cfe-45d6-a3eb-f0d144b4e203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>953ab94d-eb49-4aec-a965-71788136099c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_MC.png</value>
      <webElementGuid>be3dab33-492c-41b7-b5fb-708e65cc377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>71a62b21-922d-4008-b2f4-b1adecb738ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>d8ff668f-abaf-45db-ae25-7215a75101bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>92ad1da4-d867-42d4-9970-0c3efac3c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>399204a0-33e8-444f-89cb-813fc823cfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33da171c-e28a-44ad-9a78-cf606e006747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>07560689-47dc-48a3-852d-4de3b26843d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_MC.png</value>
      <webElementGuid>dbcc875f-adf9-4031-b629-f11357fcb6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>4b1bc592-7556-4cd5-a411-ac366ec7bc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 1</value>
      <webElementGuid>88e1a8da-7988-4066-9943-570de53eb7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-1_QC.png</value>
      <webElementGuid>74f68fcc-547f-4ddf-999a-3d3507b5801f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>05f04185-c76f-4c69-add3-a468f0a74938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div/img</value>
      <webElementGuid>64ef1cbd-b322-4504-a98b-8f478663095b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Room 1']</value>
      <webElementGuid>46ae9123-d67d-471f-b95a-96b6ddc755ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>cdc42e18-fba7-4636-b68b-07a5ee1e2f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Room 1' and @title = 'Room 1' and @src = '/images/new/dragonstone/ROOM-1_QC.png']</value>
      <webElementGuid>bf0c6620-882c-47ed-9d79-7ccf78af1ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
