<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>bd9cbbdb-2aeb-48d2-82a4-804ce81ca4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Room 3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28f3be8b-8b6e-4202-974d-519d5afc1987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_QC.png</value>
      <webElementGuid>be27cd58-89a3-4694-8046-4aed1e12f275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_MC.png</value>
      <webElementGuid>3e40d018-6ecf-45dd-93aa-8129004a8d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 3</value>
      <webElementGuid>80369d7e-c6b6-4585-88ea-f54333525c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 3</value>
      <webElementGuid>a2c95f30-9190-497c-b7ec-7d54db890f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_QC.png</value>
      <webElementGuid>d5ca8ad7-ef59-4be2-aba1-d5a9c1877320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>6ebab189-1b59-4645-aa4a-999fd038d5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>036cda26-498a-4955-b0d7-8d6cffc9c536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_QC.png</value>
      <webElementGuid>844de706-5ae6-41b5-aad1-2d31aa6d0548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_MC.png</value>
      <webElementGuid>5f85963e-9a56-48ac-9dff-af717a894d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 3</value>
      <webElementGuid>cea1d7d0-8ea6-413a-9a77-ede89d2512ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 3</value>
      <webElementGuid>512ab2a9-1ff5-416c-8a2e-16ca9d705a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-3_QC.png</value>
      <webElementGuid>13c78adf-5e3b-41d3-aec6-d49ced970ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>e0cc171c-799b-4a50-8fe7-680f0121461f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[3]/img</value>
      <webElementGuid>296e8092-d22e-4fd1-bbe5-59a229d19306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Room 3']</value>
      <webElementGuid>eee525b7-41b0-4d1b-b052-c8aff9bb892c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/img</value>
      <webElementGuid>70ab8324-9d10-4b86-9767-fe359045b9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Room 3' and @title = 'Room 3' and @src = '/images/new/dragonstone/ROOM-3_QC.png']</value>
      <webElementGuid>8045bc92-4182-4618-96f0-547018c5c26c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
