<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>0cd3e905-b53e-4b1c-9358-7134f0107a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Mission Amazon Logo'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.modal-title > img[alt=&quot;Mission Amazon Logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d249a115-b251-4015-af50-3308fc771b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/mission-amazon/MA-logo-781x92.png</value>
      <webElementGuid>d665c921-0cb0-46c2-860f-6b4f7cd5fa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Mission Amazon Logo</value>
      <webElementGuid>cc85328b-c990-44f8-9285-584ff050dabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mission Amazon Logo</value>
      <webElementGuid>6e04b29e-eacb-4db0-8b96-6f03896f1d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>859b5209-910b-467c-895d-c5453845622f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modalFixed&quot;]/div[@class=&quot;modal show&quot;]/div[@class=&quot;modal-dialog modal-alert show&quot;]/h3[@class=&quot;modal-title&quot;]/img[2]</value>
      <webElementGuid>9ba4646c-6860-4521-9003-ebcff0989d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd43392e-4863-4b71-8797-4a0bfff4b73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/battleground/BTG-logo-343x67.png</value>
      <webElementGuid>61494e3f-e09d-44fe-b92f-a5d47214385e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Battleground Logo</value>
      <webElementGuid>b68f6374-3277-4e5c-be20-f19b34ac5357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Battleground Logo</value>
      <webElementGuid>b7b09c64-7b48-4252-83bb-8f5b0b8f256b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-logo-top-left mq-animation anim-fade-in&quot;]/img[1]</value>
      <webElementGuid>83c5a2f1-9f5f-4510-a1fc-88125210e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>92305da7-6cdd-48c1-b526-94533864117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/DS-game-logo.png</value>
      <webElementGuid>33eb5316-da23-4b24-b125-e0ac1f4ce695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dragonstone Game Logo</value>
      <webElementGuid>f5c434dd-ad3a-48dc-b9db-98dafd1c04ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dragonstone Game Logo</value>
      <webElementGuid>7b771eee-8d0a-4493-80e2-1527a10e5887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-logo-center mq-animation anim-fade-in&quot;]/img[1]</value>
      <webElementGuid>fdcbc40e-2c15-4a17-ac7a-42448fb5a86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>601d4a73-e1e5-4315-818c-a6580ea1817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/DS-game-logo.png</value>
      <webElementGuid>6ae26d49-3aae-43b5-8c0a-f12c44a4c6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dragonstone Game Logo</value>
      <webElementGuid>516a5ab5-1422-4eb8-8887-fd1f655626c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dragonstone Game Logo</value>
      <webElementGuid>807201bf-f7b6-4cf1-9503-7dd0dcfaf0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-logo-center mq-animation anim-fade-in&quot;]/img[1]</value>
      <webElementGuid>2ac6ba94-8309-43e5-9038-c7c4de1ba2c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Mission Amazon Logo'])[3]</value>
      <webElementGuid>951b2044-bc82-4565-ae2d-97299240bc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/img[2]</value>
      <webElementGuid>afd0e89c-cfc3-472e-bed9-e486c2dd9ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/new/mission-amazon/MA-logo-781x92.png' and @alt = 'Mission Amazon Logo' and @title = 'Mission Amazon Logo']</value>
      <webElementGuid>ead9e79e-c6e3-4ddf-b052-99b031ef1802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/div/div[3]/img</value>
      <webElementGuid>85769251-bcf7-4a73-95dc-ee90d0ab1d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Battleground Logo']</value>
      <webElementGuid>9aaa1ee3-5809-4e79-a9d1-15134c4658d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>7ee908f4-7093-412b-b0e0-94bd3268ee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/new/battleground/BTG-logo-343x67.png' and @alt = 'Battleground Logo' and @title = 'Battleground Logo']</value>
      <webElementGuid>85bc3352-2c19-448e-8750-e61a606e41bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/div/div[2]/img</value>
      <webElementGuid>433891f8-ffc1-42d2-99f6-1b3567e2306f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dragonstone Game Logo']</value>
      <webElementGuid>befef5ff-4aa5-49c4-8886-d0387524cf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>4e9b8284-acad-41c7-b1c4-a971a5952fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/new/dragonstone/DS-game-logo.png' and @alt = 'Dragonstone Game Logo' and @title = 'Dragonstone Game Logo']</value>
      <webElementGuid>b4d158b7-c792-486d-b4fd-ccc3f7f8d53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
