<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>2443e835-9d5a-43c0-bc46-cf82658fff72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Room 4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35870988-c3ca-48cd-878c-686eca1e9b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_QC.png</value>
      <webElementGuid>e20e161e-1b76-49f6-8b9d-64a411209ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_MC.png</value>
      <webElementGuid>16298b5b-8290-4368-beac-e26dd13a2a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 4</value>
      <webElementGuid>28fae074-d3b4-4395-b8fd-c4c63a5a4184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 4</value>
      <webElementGuid>511b742c-46b9-4f64-bde0-b8aeedc85f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_QC.png</value>
      <webElementGuid>86bbcb5c-9845-4087-8846-297b4de50d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>34bd081a-56e6-43fa-a53f-ab1d04c519a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ecac31a-b8b3-4d67-954d-35c028f745c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_QC.png</value>
      <webElementGuid>80938bf9-abf7-4470-b08a-6f1d23003b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_MC.png</value>
      <webElementGuid>32fe080d-6976-4ed7-9106-e1c00640e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 4</value>
      <webElementGuid>d9ca48c7-fe0a-4d35-bf1d-5a0334e8ecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 4</value>
      <webElementGuid>279771f9-8c9c-402c-b086-25999fee5c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-4_QC.png</value>
      <webElementGuid>84391fc7-2dae-4b43-857c-e6c097a89c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>9a217264-8bf7-4d5e-aa1e-77bbe002ab7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[4]/img</value>
      <webElementGuid>cbce39bd-5c06-4512-980e-c0cfb563e6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Room 4']</value>
      <webElementGuid>a9949194-7abe-4025-b2d7-28dcd8387d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img</value>
      <webElementGuid>01001a6a-1424-43b6-88bb-b44623a8f2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Room 4' and @title = 'Room 4' and @src = '/images/new/dragonstone/ROOM-4_QC.png']</value>
      <webElementGuid>f6f0e1f7-7535-4873-8608-28406cf1ff9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
