<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>6592c3fc-2d01-45fe-819b-9540a290d875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[6]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Room 6&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed7d0a42-8674-481f-8a60-19e6dd210f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_QC.png</value>
      <webElementGuid>ec64bcea-48b3-423e-999a-ed1bae7cdbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_MC.png</value>
      <webElementGuid>04be76a2-ee93-4561-95ec-76774c60b5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 6</value>
      <webElementGuid>ed4ff673-0bf1-45d7-b89a-bd73e8a4fae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 6</value>
      <webElementGuid>783a78df-0035-4955-827a-20bdb9687edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_QC.png</value>
      <webElementGuid>6c3caea9-a6a7-406c-92fc-40f4cb5b3225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>a554082b-9cbf-477d-9826-fe2fd19c756c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>435fea87-6884-4d64-ae6c-62094cbae92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_QC.png</value>
      <webElementGuid>18cc03b1-26ff-4240-9d02-be5d0b854aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_MC.png</value>
      <webElementGuid>7f792e38-bb23-467a-973e-d79a2d178f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 6</value>
      <webElementGuid>e411c64d-4611-4e17-a0f2-a0fb842ce79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 6</value>
      <webElementGuid>08c51007-4f8a-44d8-bae6-74d2449fd709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-6_QC.png</value>
      <webElementGuid>e73b3712-b2ce-4dc6-b1a2-b769f90a356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>7a6e6c93-890d-47f1-945f-6c569cf26abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[6]/img</value>
      <webElementGuid>c0908146-572a-4db7-aaed-0a0f82dca849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Room 6']</value>
      <webElementGuid>2a1b4ed8-9cf5-4c44-8ef2-a15a7602aec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/img</value>
      <webElementGuid>4e505e1a-b2f6-42d6-9211-2d2bd327520d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Room 6' and @title = 'Room 6' and @src = '/images/new/dragonstone/ROOM-6_QC.png']</value>
      <webElementGuid>9091a878-f89d-4a5b-a8c2-4702055eb0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
