<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>3e0b22a0-7e19-4bc9-b1e8-ac22d3534d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[5]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Room 5&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52969b5c-fb37-4ae3-8add-ec2c7dd733d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_QC.png</value>
      <webElementGuid>7c8f5aac-aecd-4338-8d41-b37786e18b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_MC.png</value>
      <webElementGuid>e748bd29-7008-478d-a5d6-834c63c55d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 5</value>
      <webElementGuid>666b3c40-b58c-498d-b60a-37f8a344960e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 5</value>
      <webElementGuid>3ae7e651-4a81-45cb-82a1-7817276d0a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_QC.png</value>
      <webElementGuid>63176698-4f3a-414c-bf86-99e68b7ab406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>433b11e4-685a-4890-a890-2728b7c966e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d94514bb-caed-4bd9-8a0d-ae5c9958d6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcqc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_QC.png</value>
      <webElementGuid>0d368d2d-85e1-49d9-9eb3-6e2ba4b5f229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcmc</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_MC.png</value>
      <webElementGuid>0d98bfae-c901-4482-adec-71470f045ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Room 5</value>
      <webElementGuid>2b2098d5-0801-4818-96d5-ad833f1448ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Room 5</value>
      <webElementGuid>0e223b99-1c4b-4b07-a375-1a750e39052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/new/dragonstone/ROOM-5_QC.png</value>
      <webElementGuid>9388f69f-a9db-499b-a686-f17692627182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;game-rooms mq-animation anim-fade-in&quot;]/div[@class=&quot;room-item mq-animation anim-from-top show&quot;]/img[1]</value>
      <webElementGuid>93b838b3-2fa9-4f64-97fa-1c284426440a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div[2]/div[2]/div[5]/img</value>
      <webElementGuid>c8645438-1f68-49be-b427-3a000a93daea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Room 5']</value>
      <webElementGuid>88ca3384-eb38-44c9-ba43-800b552d39b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/img</value>
      <webElementGuid>cbc1d9ae-5ce0-4933-9ed6-71772ac4f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Room 5' and @title = 'Room 5' and @src = '/images/new/dragonstone/ROOM-5_QC.png']</value>
      <webElementGuid>2225e61a-afdd-4ff8-ba05-1ff65ba38b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
