<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Jump into 90-second player vs player batt_4f9fd6</name>
   <tag></tag>
   <elementGuidId>e2049919-9b32-4691-9a43-c1f9352b1f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-ced714e1']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-ced714e1 > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>291fa098-ad21-46ad-b04c-e9a1367cb829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jump into 90-second player vs player battles with up to 5 opponents. Be the last one standing to walk away with the entire prize pot!</value>
      <webElementGuid>995cce35-958d-43cf-a537-bbf67854999a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-ced714e1&quot;)/p[1]</value>
      <webElementGuid>940f4618-50ef-429a-aeab-24328decc26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-ced714e1']/p</value>
      <webElementGuid>5d17be9e-3750-4c30-a61b-fe46e918b541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINNER'])[1]/following::p[1]</value>
      <webElementGuid>f65cc89a-5d77-4e7c-ada6-cdb594533671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::p[1]</value>
      <webElementGuid>a0d1b30c-9f14-4329-b7b1-d0bb6002d418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jump into 90-second player vs player battles with up to 5 opponents. Be the last one standing to walk away with the entire prize pot!']/parent::*</value>
      <webElementGuid>a6ac852f-af7b-47c1-b792-360d6ccbb8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/p</value>
      <webElementGuid>ffdb7a15-53aa-49b5-91c6-d20c77b5fe37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Jump into 90-second player vs player battles with up to 5 opponents. Be the last one standing to walk away with the entire prize pot!' or . = 'Jump into 90-second player vs player battles with up to 5 opponents. Be the last one standing to walk away with the entire prize pot!')]</value>
      <webElementGuid>0ad4333f-9788-4112-bcc9-73a21d7f42d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
