<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HOW TO PLAY</name>
   <tag></tag>
   <elementGuidId>72df5c99-6754-4e3f-a955-c0f8c436f06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/div[2]/div/div/div[4]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.overlay-button.mq-animation.anim-from-right > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>acfaf7d6-b10f-4413-8176-c9daa8ef27db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOW TO PLAY</value>
      <webElementGuid>5f8e7e28-79ed-44f6-93f8-8a43d25e8e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-buttons&quot;]/div[@class=&quot;overlay-button mq-animation anim-from-right&quot;]/span[1]</value>
      <webElementGuid>3ff05a0d-dcc5-4fa0-80ea-c564e0db3aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4acdd6f6-788a-4b58-a471-b489e2399193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOW TO PLAY</value>
      <webElementGuid>1cd2a183-3828-4896-99ee-80d1dded929f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-buttons&quot;]/div[@class=&quot;overlay-button mq-animation anim-from-right&quot;]/span[1]</value>
      <webElementGuid>c66e98a9-4535-49c7-abfe-bb4f339dc481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0de3b465-c019-42ca-8c57-760d85233b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOW TO PLAY</value>
      <webElementGuid>9676b291-1931-4033-af77-b74f34e35cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-buttons&quot;]/div[@class=&quot;overlay-button mq-animation anim-from-right&quot;]/span[1]</value>
      <webElementGuid>25b728b9-5954-47d9-b8c3-d4e839f7d6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8da947f-5115-4a58-806a-eb1331546c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOW TO PLAY</value>
      <webElementGuid>617c821f-3107-4f2e-824a-09966a1d2a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-buttons&quot;]/div[@class=&quot;overlay-button mq-animation anim-from-right&quot;]/span[1]</value>
      <webElementGuid>026030fe-e13f-4410-b0a7-00a052b0351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78350ce8-6bbb-495f-82ac-4a1eedc88714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOW TO PLAY</value>
      <webElementGuid>4259b06a-57ac-4521-ba43-4337c6b75ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-cover&quot;]/div[@class=&quot;cover-container&quot;]/div[@class=&quot;overlay-buttons&quot;]/div[@class=&quot;overlay-button mq-animation anim-from-right&quot;]/span[1]</value>
      <webElementGuid>30244f96-8d31-4501-9c44-efafa8ddfb3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div[2]/div/div/div[4]/div/span</value>
      <webElementGuid>78e99fc0-951a-4c1e-ad8f-8b3ab3bbfa1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASINO'])[2]/following::span[1]</value>
      <webElementGuid>91c4e08d-0ba7-4c92-ab76-636e098fa158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFER FRIENDS'])[2]/following::span[1]</value>
      <webElementGuid>631f17f1-89fa-4017-b35d-0e13457cdba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME HISTORY'])[1]/preceding::span[1]</value>
      <webElementGuid>7f27be7b-f329-4933-b86e-8b4f5d92bfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK TO LOBBY'])[1]/preceding::span[2]</value>
      <webElementGuid>1d0b2051-41fd-44a1-bd00-94498158d8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOW TO PLAY']/parent::*</value>
      <webElementGuid>51b91f6b-221f-4633-942d-968606c7ec17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span</value>
      <webElementGuid>88cf49fa-8bf9-49fa-8387-779b52871385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'HOW TO PLAY' or . = 'HOW TO PLAY')]</value>
      <webElementGuid>604b8d04-625f-4117-a9d5-7efc41c4244a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
