<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crypto</name>
   <tag></tag>
   <elementGuidId>15307658-e61b-49a5-a7ee-707608777b0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1739']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1739 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5758f3a-b2ec-40a6-8c4d-fd950c5331f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/crypto/</value>
      <webElementGuid>2e5553e2-488d-4536-a493-b8be8dd3c30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crypto</value>
      <webElementGuid>cb07d832-6166-4b2b-9588-2bd24501f843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1739&quot;)/a[1]</value>
      <webElementGuid>09e13ef2-c5ba-4f17-a87b-fd3d7697c487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8550bcd1-19e0-4de2-a4f2-e965ae68c003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/crypto/</value>
      <webElementGuid>e9350eea-11b8-44d8-b368-1b5d594339c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crypto</value>
      <webElementGuid>917f5479-b725-4e38-8792-588857894256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1739&quot;)/a[1]</value>
      <webElementGuid>2f72c06e-a4d1-465c-85e7-c238a8a70c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1739']/a</value>
      <webElementGuid>2e9dd0ff-6fb5-4fa3-8782-f6fc6fe78a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Crypto')]</value>
      <webElementGuid>5c675628-5928-4afc-8653-bd5c939c5b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::a[1]</value>
      <webElementGuid>39f181d7-b98b-4b88-800b-178fc6354175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Policy'])[1]/following::a[2]</value>
      <webElementGuid>168d85a0-bfe4-4ef5-b981-c511e2a06cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We', &quot;'&quot;, 're Online!')])[1]/preceding::a[7]</value>
      <webElementGuid>24c5277f-5525-4c7b-a3af-e93fef55db10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'menu-item-1739', '&quot;', ')/a[1]')])[1]/preceding::a[7]</value>
      <webElementGuid>0ea7b201-05ca-4757-a039-f09db58fc750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crypto']/parent::*</value>
      <webElementGuid>f9c3e405-3dba-46c4-905b-a9af1b4fa9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/crypto/')]</value>
      <webElementGuid>65f6087f-8e54-4abc-9665-a14a0a499038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[6]/a</value>
      <webElementGuid>21e55a4e-87a4-41d6-a3e6-c69e09ed5d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/crypto/' and (text() = 'Crypto' or . = 'Crypto')]</value>
      <webElementGuid>e44faad6-30e3-4da6-bb15-8e61dfb67010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
