<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GET REWARDED</name>
   <tag></tag>
   <elementGuidId>097b4f3e-e4a2-4f5a-b22a-3d3091c51b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotion-popup']/div/div/div[2]/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.promotion-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc65545a-ec43-455c-9307-c5e255fd2d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/refer-friends/</value>
      <webElementGuid>91f78bab-d295-4da5-8dbd-85984330c4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button promotion-button</value>
      <webElementGuid>4ccb0f48-4cf8-4e6a-8143-a91909857403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GET REWARDED</value>
      <webElementGuid>73577339-0cb2-4029-b640-938a85b7bbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion-popup&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;description&quot;]/div[@class=&quot;button-wrapper&quot;]/a[@class=&quot;button promotion-button&quot;]</value>
      <webElementGuid>156adacd-a27c-4704-99da-df831a70252c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b09b1cdc-1dbb-4219-9244-43b449001a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/refer-friends/</value>
      <webElementGuid>67bf0346-1ed7-4689-927f-97f424f20007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button promotion-button</value>
      <webElementGuid>0111d957-3ea8-4e0f-b345-e6f5238276ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GET REWARDED</value>
      <webElementGuid>fab107e9-bde6-46c2-9440-228b5a4a56ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion-popup&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;description&quot;]/div[@class=&quot;button-wrapper&quot;]/a[@class=&quot;button promotion-button&quot;]</value>
      <webElementGuid>68301348-d494-40c7-bfff-0eca6b7539f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotion-popup']/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>3a0da4ed-0394-46f8-91af-4df8762d9381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'GET REWARDED')]</value>
      <webElementGuid>95a879f3-c263-4b07-9b6f-bfed3b4dcd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[2]/following::a[1]</value>
      <webElementGuid>d796ccab-fb2b-49ef-8590-23c925f19b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit'])[3]/preceding::a[1]</value>
      <webElementGuid>96e34aa5-d169-4437-b1eb-b108e81be5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::a[1]</value>
      <webElementGuid>5910db2a-92f9-4925-834c-51f217fea049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GET REWARDED']/parent::*</value>
      <webElementGuid>fd216179-807c-4f93-9f56-38da975f3874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/refer-friends/')])[2]</value>
      <webElementGuid>0351a72d-05bc-47a1-bb5c-c64ebadd80ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/a</value>
      <webElementGuid>133f9f3e-7c01-44f5-b83a-e711e586ec12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/refer-friends/' and (text() = 'GET REWARDED' or . = 'GET REWARDED')]</value>
      <webElementGuid>4c4b7ce2-1e6c-4b19-bd69-23ad5c7efe06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
