<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tap to unmute_ytp-cued-thumbnail-overlay-image</name>
   <tag></tag>
   <elementGuidId>85acca67-3430-4070-a44f-a9c795d8fa3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ytp-cued-thumbnail-overlay-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93f5d695-b20f-4aec-81e2-f7c8ba754b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-cued-thumbnail-overlay-image</value>
      <webElementGuid>1f604548-4e71-45c7-91ad-38575f9a413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-cued-thumbnail-overlay&quot;]/div[@class=&quot;ytp-cued-thumbnail-overlay-image&quot;]</value>
      <webElementGuid>a700f8df-0301-4acc-87e0-ba3836891c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe__embed-responsive-item</value>
      <webElementGuid>66d07b45-259d-4be0-b859-9883a792e0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[4]/div</value>
      <webElementGuid>c70648f1-e2e0-4410-a314-6d1f9c1e293e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>e922449b-5eb9-4c37-92e2-e256fb100cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
