<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_THIS IS A TEST MESSAGE IGNORE IT PLEASE_1</name>
   <tag></tag>
   <elementGuidId>a2903455-8088-4371-a71b-46faf096407e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1664895026592']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6df3dfca-5c0a-4637-bd38-cd87f8260af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msgbx </value>
      <webElementGuid>80a4458f-937e-429f-85de-aeff4e1bafff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>proptype</name>
      <type>Main</type>
      <value>msgbx</value>
      <webElementGuid>fbc02391-1e93-4f8d-b5b1-8f4f0dfc6fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> THIS IS A TEST MESSAGE IGNORE IT PLEASE.</value>
      <webElementGuid>39fc78e9-5299-4f43-88e1-cf173925fdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1664895026592&quot;)/div[@class=&quot;msgbx&quot;]</value>
      <webElementGuid>cfd29267-c9fb-400f-9bf2-f4a14a2b0ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>da70f025-7180-41a7-b25d-950ee439a824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1664895026592']/div[2]</value>
      <webElementGuid>c60f9fe0-52e2-4bf1-8827-ee6b4dbcf13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST_ACCOUNT'])[1]/following::div[1]</value>
      <webElementGuid>fc0b3983-1373-4150-af52-633a3eb7af63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait while we connect you to our support representative.'])[1]/following::div[6]</value>
      <webElementGuid>975f6b0f-ced2-4b54-a487-17d81c16f8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting to connect...'])[1]/preceding::div[6]</value>
      <webElementGuid>0356d6bd-628a-4857-a1ad-d4228a4c691d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]</value>
      <webElementGuid>f489c11d-d702-486b-a33d-169d89e4fbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' THIS IS A TEST MESSAGE IGNORE IT PLEASE.' or . = ' THIS IS A TEST MESSAGE IGNORE IT PLEASE.')]</value>
      <webElementGuid>fcd7b9ad-2457-47df-85dd-33a971a45d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
