<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , showsiqconv, , ))_showsiqconv</name>
   <tag></tag>
   <elementGuidId>0bfa8d69-5cba-40de-a038-18f8c58a8f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showsiqconv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#showsiqconv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>725e4bb8-7b51-42b0-90c0-7ef5e261b271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>siq-convback sqico-larrow</value>
      <webElementGuid>58f2a5d7-c920-4d98-9f9d-5615af96cef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showsiqconv</value>
      <webElementGuid>4fa447aa-127c-460e-b46f-a27879e02da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>documentclick</name>
      <type>Main</type>
      <value>showconvlist</value>
      <webElementGuid>8415d8d1-7439-4707-91da-5791ca6c5322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showsiqconv&quot;)</value>
      <webElementGuid>316fcbc3-bdb0-47ee-b7d6-65614e6487ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>1a4d5ecb-e203-4b93-911d-0bb9bb03b2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='showsiqconv']</value>
      <webElementGuid>3423cf23-a965-4e38-b8e8-51721ad9cf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='window-ribbon']/header/div/div</value>
      <webElementGuid>1713edde-bc22-44b7-9d2f-0a69396c8c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div</value>
      <webElementGuid>fdf22559-dfba-4053-aee2-66db80462801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'showsiqconv']</value>
      <webElementGuid>299b0712-75fe-4308-ba84-319e7ba8fdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
