<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Worlds_slick-next slick-arrow</name>
   <tag></tag>
   <elementGuidId>31ce00ec-1c80-4e5c-a001-c1544e277b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-5204baa3']/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slick-next.slick-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>105cc9f7-9fae-4cdd-95d5-f1367f0d8b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>d9bc5512-9176-4d8e-9159-6193afd40a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>8b4d8b41-fba0-4e78-ac38-b2ff76d6db9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d403dde8-92c2-4914-8aaf-adc440bb6892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>2b0720be-dcdb-4e02-a0f1-7d865e64a4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>378e2bcd-fa04-4b79-a968-0177d3e18d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf377279-b060-4af9-8b17-2d3a3f55d578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>68957f75-8a9e-49f5-b528-abf3e523e840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>2b9f2bed-bd0e-4bde-9530-20fc481ac841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12e38aa6-f51a-4a0f-af9f-032bf57ea085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>69b27bd9-88ab-4a25-8fc3-80ac6ba1a8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>16c28711-a7bb-493d-a3c9-6276ad87655c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b91a8278-f321-4ee7-90e5-3880f92fd435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>03500a4d-eafd-45e6-b26c-aa85cc668f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>fbdba2f2-6bfc-4cdb-81fc-d93ade2b59df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1933bf19-9b6f-4520-aab4-7899be3c1ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>307360ec-e754-4274-84cf-7a6adb5b24ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>f071e7d4-0936-4d33-accf-152f2877e6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31668fa6-d110-4bf6-97a7-5c1be6f18cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>7bb0c510-b032-45d4-964c-fb066d857eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>d2ad6c07-869e-4a0c-bf39-592653f2af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f61d191e-cbd1-401c-9b76-43eb659535e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>cd29ba28-fa38-460e-a635-7a8740c955cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>aed96d32-fae5-44b8-8e4c-e4baa1138dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed027fca-728a-4dd5-b2c1-a03286c56205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>92e44292-be62-4516-8b6a-f61588b1de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>5462ad32-3701-478a-b92b-d0019eb0a36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22144c1d-7da0-450a-b090-9a94eb3aac27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-next slick-arrow</value>
      <webElementGuid>04f00f07-dfb4-4ed0-94b2-ab78816539f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-5204baa3&quot;)/div[@class=&quot;explore-worlds-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-next slick-arrow&quot;]</value>
      <webElementGuid>ff81442d-753b-4f19-b0d7-ba8d29c1b16a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-5204baa3']/div/div[3]</value>
      <webElementGuid>f5332ee9-3f8f-42e7-a383-772ccfa3337c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/div/div[2]/div/div/div[3]</value>
      <webElementGuid>557cdb53-6d02-4fae-9d83-58f1340090fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
