<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Explore our giveaways, discounts, and e_0afb6b</name>
   <tag></tag>
   <elementGuidId>3a973ea2-85e7-4213-9511-bef856aeff9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-08eac28f']/div/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8384ae20-6967-4e32-bd80-c40c8571d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-wrap</value>
      <webElementGuid>d39b2ac3-ec6c-4326-be5e-00227c6d6a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-08eac28f&quot;)/div[@class=&quot;promotion-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;promotion-slide slick-slide slick-active&quot;]/div[@class=&quot;promotion-wrap&quot;]/div[@class=&quot;img-wrap&quot;]</value>
      <webElementGuid>432ef6ff-ffae-4be3-9cbd-ae9a9753d162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-08eac28f']/div/div/div/div[2]/div/div</value>
      <webElementGuid>6d80d199-d3ef-4b73-bc37-ad6735e40dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore our giveaways, discounts, and exclusive offers to load up on coins!'])[1]/following::div[12]</value>
      <webElementGuid>b93a085b-e9f0-4736-9325-a6935df93345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rewards'])[1]/following::div[12]</value>
      <webElementGuid>901b84ea-61d4-4f0e-a665-08fc1bcee3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Worlds'])[1]/preceding::div[2]</value>
      <webElementGuid>07588345-071e-4452-9481-2c7043f5ae8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>18765d51-d6ba-4e40-8ac7-1ac52195467e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
