<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hot Games_slick-prev slick-arrow</name>
   <tag></tag>
   <elementGuidId>964e5406-ff03-479c-8158-3ced20bc2cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-814ff268']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row.slick-initialized.slick-slider > div.slick-prev.slick-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c249f47d-5b06-4674-aad1-b8c80728f80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-prev slick-arrow</value>
      <webElementGuid>9b1eb147-e207-4a55-afe4-50cfbba6877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-814ff268&quot;)/div[@class=&quot;casino-games-list-wrap slider&quot;]/div[@class=&quot;row slick-initialized slick-slider&quot;]/div[@class=&quot;slick-prev slick-arrow&quot;]</value>
      <webElementGuid>0557730b-2028-4e8d-b882-4a4eb678b34b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-814ff268']/div/div/div</value>
      <webElementGuid>12b3746c-01ad-420b-83dd-18f8cc1de3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>49cc157b-5f9a-4b33-ab5c-7a07b641a412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
