<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TEST_ACCOUNT</name>
   <tag></tag>
   <elementGuidId>07a5fa63-0b3a-4a02-a53a-5d9d18d82477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1664895026592']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.siq-visitor-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8090c76-61cb-4a5a-adc2-14667c7aed0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>purpose</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>83656dc5-452a-4c3a-b53f-865b3e16f3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sendertype</name>
      <type>Main</type>
      <value>visitor</value>
      <webElementGuid>95c775d0-ec0d-4ee8-9bdd-4a360cb43544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>siq-visitor-name</value>
      <webElementGuid>bbf7a864-ab76-4ae7-a187-fb0a501a73c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>documentclick</name>
      <type>Main</type>
      <value>userdetails</value>
      <webElementGuid>c7149a44-bb2e-430d-99e4-3af98e207f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST_ACCOUNT</value>
      <webElementGuid>aaf7a304-601e-457f-a9e8-cb6d22756508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1664895026592&quot;)/div[@class=&quot;siq-visitor-name&quot;]</value>
      <webElementGuid>6e58fb24-3c12-4a94-abe8-fa5c541a78ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>a40e3795-ed24-4aa3-8941-fb62f8e0eb4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1664895026592']/div</value>
      <webElementGuid>6a5750e6-4588-4e2d-b4e6-f5ef467f7ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please wait while we connect you to our support representative.'])[1]/following::div[5]</value>
      <webElementGuid>d5a010b7-eb85-4cdf-8697-1dff3fee57df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat with us now!'])[1]/following::div[8]</value>
      <webElementGuid>c0d52918-315b-4e7d-8a08-e4022346fd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THIS IS A TEST MESSAGE IGNORE IT PLEASE.'])[1]/preceding::div[1]</value>
      <webElementGuid>fd26cf83-3fb0-4e2e-8785-e24cf887307a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting to connect...'])[1]/preceding::div[7]</value>
      <webElementGuid>dd4c21cb-68e9-4208-b409-d5193efde963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TEST_ACCOUNT']/parent::*</value>
      <webElementGuid>3385618a-7dcf-4a9e-9fcf-1d863f1b5ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>e04c5bd3-bc3d-4715-b24c-3ad615a9d180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TEST_ACCOUNT' or . = 'TEST_ACCOUNT')]</value>
      <webElementGuid>7223437c-4c36-47fd-84e5-f99fe0c95266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
