<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Start Chat</name>
   <tag></tag>
   <elementGuidId>a7f1c559-cbca-4a8b-9438-dd85f99e5d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//em[@id='sqico-send']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sqico-send</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>ea5ed206-1ba8-47a9-8e1a-a1890bf02248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sqico-send siq-send-button</value>
      <webElementGuid>c7558148-a68b-43cb-b723-39e6bb8917f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>chatid</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>99e381f7-f8aa-44c0-a110-d838fbe68b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sqico-send</value>
      <webElementGuid>8af53f64-66f3-4957-8d84-06cba07ff534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>proptype</name>
      <type>Main</type>
      <value>sqico-send</value>
      <webElementGuid>a68c1c96-c422-417d-8aea-3ca0c223adb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>documentclick</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4ab739b2-290c-4b93-b544-bd27c2b3b0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Chat</value>
      <webElementGuid>fcb0ea33-eab9-49df-871f-ba0d923d6b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sqico-send&quot;)</value>
      <webElementGuid>5ae274dc-a925-4219-8d71-7c02936906d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>1b02be1e-ba67-47d3-a496-051b6d3ce23a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//em[@id='sqico-send']</value>
      <webElementGuid>67168aa4-7ecc-4547-8797-3811afaa3409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='window-ribbon']/footer/div/em</value>
      <webElementGuid>1d910028-bcb3-49a5-84ce-732cbedf59d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat with us now!'])[1]/following::em[3]</value>
      <webElementGuid>9c1510f3-5034-4630-b29f-8bb1817f19c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'sqico-send', '&quot;', ')')])[1]/following::em[3]</value>
      <webElementGuid>12c46d66-c45a-4156-9fca-26bafd086fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Chat']/parent::*</value>
      <webElementGuid>152e5d02-062c-4193-a518-b7fdb0df8a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/em</value>
      <webElementGuid>ec449d97-1fd7-4fc3-b832-fe3542baa7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[@id = 'sqico-send' and (text() = 'Start Chat' or . = 'Start Chat')]</value>
      <webElementGuid>693bc286-de29-460b-8bda-bf8b15b82015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
