<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Casino</name>
   <tag></tag>
   <elementGuidId>56a03cd7-3924-4298-9785-8fe077c9161e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-3976cf1d']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.vce-google-fonts-heading-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>73b8960e-c504-42cd-ab74-5080a4a77efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-google-fonts-heading-inner</value>
      <webElementGuid>5cab1170-c770-485f-9750-f547cb03ec6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casino</value>
      <webElementGuid>cd44b793-43f5-4cc4-81bf-30da858f68cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-3976cf1d&quot;)/h1[@class=&quot;vce-google-fonts-heading-inner&quot;]</value>
      <webElementGuid>cd13a014-4183-433b-af56-e40a812b7306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-3976cf1d']/h1</value>
      <webElementGuid>7c87ebc1-faa7-43e3-ab81-082a620dc7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Worlds'])[1]/following::h1[1]</value>
      <webElementGuid>8847d0e6-d539-45bf-a397-88b5cd0bc15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose from Slots, Blackjack, Roulette and much more - no purchase required!'])[1]/preceding::h1[1]</value>
      <webElementGuid>097ce35c-5bb9-4e37-8148-c090af244db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot Games'])[1]/preceding::h1[1]</value>
      <webElementGuid>0fb5f95e-789c-40c0-8246-f7d0774ec0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/h1</value>
      <webElementGuid>45d9b552-0787-456f-8012-3be4df2b8360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Casino' or . = 'Casino')]</value>
      <webElementGuid>342fb65d-ceaa-4842-9db8-5f0c87004b36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
