<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_WINNER TAKES ALL</name>
   <tag></tag>
   <elementGuidId>ea2b0dcf-435d-4983-8a41-da34d425ff23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-77f6703b']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-77f6703b > h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8b124c8c-d1e5-476f-a7e5-c8d761e32b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINNER TAKES ALL!</value>
      <webElementGuid>86d95b29-f35f-49b0-a1eb-9e05fc982975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h1[1]</value>
      <webElementGuid>aec7a569-5be9-4b83-a10a-ae8898552ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c6e00aee-2930-4dd7-9b1e-7a0b98984225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINNER TAKES ALL!</value>
      <webElementGuid>17336455-b74a-4010-b1c1-6e84d8b252de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h1[1]</value>
      <webElementGuid>97487bb2-b0f7-4ad5-a6f4-3f79ed5e46c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bff730c8-f6f9-43e6-a51f-0b19c40de5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINNER TAKES ALL!</value>
      <webElementGuid>deaa5ed0-2b32-454e-8607-84138a97fafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h1[1]</value>
      <webElementGuid>328c6de2-c0f2-44e9-97ac-e326afee873c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>1a0ec3d3-1f37-4c37-b687-e478824db13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINNER TAKES ALL!</value>
      <webElementGuid>13df89e3-db3b-48d9-af3e-7696464ef299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h1[1]</value>
      <webElementGuid>f51883ff-3817-4f44-98cf-66579cc53dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-77f6703b']/h1</value>
      <webElementGuid>c0baeccb-2af4-4ec7-9134-c30a870fdb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast and secure withdrawals guaranteed'])[1]/following::h1[1]</value>
      <webElementGuid>6ebb8a44-db1e-410e-bf13-cd5a9f794ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn Coins Into Crypto'])[1]/following::h1[1]</value>
      <webElementGuid>01aeb4a3-723f-4a4c-acf4-ca08c092fda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[4]/preceding::h1[1]</value>
      <webElementGuid>e9634af0-61af-4429-b53e-d911e5adc95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[2]/div[2]/div/h1</value>
      <webElementGuid>ca1e68ff-7e6e-4dc6-ace4-23162ce12e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'WINNER TAKES ALL!' or . = 'WINNER TAKES ALL!')]</value>
      <webElementGuid>a47b19e6-29e6-48be-943f-8f6002cf6b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
