<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Choose from Slots, Blackjack, Roulette a_534126</name>
   <tag></tag>
   <elementGuidId>d4ae0ddf-7aa5-418e-afcd-6a1ed315654a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-0e8a5add']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-0e8a5add > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>61fd486f-5d03-45bd-b0d5-e2f54b63bb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose from Slots, Blackjack, Roulette and much more - no purchase required!</value>
      <webElementGuid>a195d716-a006-427a-8839-14ff678bd729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-0e8a5add&quot;)/h4[1]</value>
      <webElementGuid>68a63fb1-a1ca-4014-942b-d7e2ecd94ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>05f66e41-e640-40aa-a1ee-ce1b80b24213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose from Slots, Blackjack, Roulette and much more - no purchase required!</value>
      <webElementGuid>5c3570c6-2842-49f8-9cf0-10a0ad9eaa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-0e8a5add&quot;)/h4[1]</value>
      <webElementGuid>e634f11d-b2d1-44d6-8dce-2bad5b8681a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-0e8a5add']/h4</value>
      <webElementGuid>ae7511a0-eac8-4417-b820-406f6b6bc9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[2]/following::h4[1]</value>
      <webElementGuid>d8dd08ef-9bb2-4460-8a8b-b5b6ffa75344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Worlds'])[1]/following::h4[1]</value>
      <webElementGuid>1f4103fd-f182-4dd3-be26-bd3ce41f8dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot Games'])[1]/preceding::h4[1]</value>
      <webElementGuid>279ad100-e606-46b4-993b-ce5a11115143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play Now'])[5]/preceding::h4[1]</value>
      <webElementGuid>c3ede7b4-82e2-4266-bab9-be7b6ad82a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose from Slots, Blackjack, Roulette and much more - no purchase required!']/parent::*</value>
      <webElementGuid>675d09b2-5562-48c1-8cdd-e93c0e62edd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/div/div/div[2]/div/h4</value>
      <webElementGuid>65cefaf4-c61e-4284-8481-67a11e63088c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Choose from Slots, Blackjack, Roulette and much more - no purchase required!' or . = 'Choose from Slots, Blackjack, Roulette and much more - no purchase required!')]</value>
      <webElementGuid>2aa34ec2-7469-467b-87f7-779364ed02a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
