<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Forgot your password</name>
   <tag></tag>
   <elementGuidId>2e7e3c58-738b-40bb-8cb9-cf6465785d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalForgotPassword']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modalForgotPassword > div.modal-dialog.modal-sm > div.modal-content > div.modal-header > h4.modal-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>67402d4b-e3f4-496d-a721-39eccc7abd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>ccf510dd-aecf-43db-bfc0-d3c487386996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>15eddc00-b65b-4f11-b86e-4a7abd5e28d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalForgotPassword&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>f6c72b2d-ae53-430c-988f-9ebc202e7872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalForgotPassword']/div/div/div/h4</value>
      <webElementGuid>b95e5339-d4f6-4656-b4fc-e832bc1c0472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number is not valid.'])[1]/following::h4[1]</value>
      <webElementGuid>962c227b-8a92-480d-996a-595da702ff33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::h4[1]</value>
      <webElementGuid>18205eb1-95e0-48a8-934f-c545722ccf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email is not valid.'])[1]/preceding::h4[1]</value>
      <webElementGuid>f0ad65aa-cb1f-46c3-9ea4-e97a90a2c8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h4</value>
      <webElementGuid>92afcd31-5437-4711-8a14-f49be722ea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>2003d1de-32b4-4e4b-8911-00c106c60d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
