<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Get Your Coins</name>
   <tag></tag>
   <elementGuidId>f909dc24-3fe5-41ce-82c1-a3f28f8d2f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-ffda5acf']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-ffda5acf > h4.vce-google-fonts-heading-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>15d4b3e6-ecdd-415d-b8bd-23766f0fb220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-google-fonts-heading-inner</value>
      <webElementGuid>af2d2dae-6eea-4d0f-8e08-445b09ce66df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Your Coins</value>
      <webElementGuid>97fa8f9e-079e-4ab3-afbf-59693f572d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-ffda5acf&quot;)/h4[@class=&quot;vce-google-fonts-heading-inner&quot;]</value>
      <webElementGuid>c2323438-d887-4354-b301-8e9a31bd3e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-ffda5acf']/h4</value>
      <webElementGuid>6ff8214c-30ec-492b-8e3a-50c2639cfd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account in 60 seconds or less'])[1]/following::h4[1]</value>
      <webElementGuid>71e53d65-3489-417d-b20f-e0e128a6f3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up For Free'])[1]/following::h4[1]</value>
      <webElementGuid>206308b6-2928-4459-ba75-f6583a276b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your FREE Welcome Pack and get playing'])[1]/preceding::h4[1]</value>
      <webElementGuid>2940f5c6-f663-4093-bcbc-b3879b9e5e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn Coins Into Crypto'])[1]/preceding::h4[1]</value>
      <webElementGuid>4933aa46-568c-483b-80f3-10650de4bb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Your Coins']/parent::*</value>
      <webElementGuid>a4912208-1f37-4599-aa39-bd6e95ac0dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/h4</value>
      <webElementGuid>7e411cec-f129-4de0-8bcb-8e1011f57c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Get Your Coins' or . = 'Get Your Coins')]</value>
      <webElementGuid>1c48b42f-0ddb-4975-b500-3500b217e4e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
