<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Hop into intense player vs player battle_e90bea</name>
   <tag></tag>
   <elementGuidId>20864f32-9d6a-4826-9b75-d07d8c95d1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-77f6703b']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-77f6703b > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>24eeccc9-b9f3-4056-92ba-6a444ac4e9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!</value>
      <webElementGuid>98de6244-41ce-4752-9a87-9bf819dc5939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h4[1]</value>
      <webElementGuid>7c40a6ed-04ca-4e14-b939-f6b3b9d83acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f6c43a6b-1784-4358-9e00-5f6e22087b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!</value>
      <webElementGuid>3cc064c9-4544-4c8e-85f7-20154e5ceb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h4[1]</value>
      <webElementGuid>467fdd6e-0544-4566-ab93-0c1a53dffdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>bdbf7b00-23f9-47d0-a002-2d49ce6394e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!</value>
      <webElementGuid>17cc18bc-953e-4040-8f95-2ecfa8a91da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h4[1]</value>
      <webElementGuid>5fa595be-2b33-4244-ae27-3fc0ed448a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0e1ae2a3-85dc-4353-aa62-c62dfb75e70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!</value>
      <webElementGuid>c0324f2f-8a6c-48a4-9284-d2a2c65b0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-77f6703b&quot;)/h4[1]</value>
      <webElementGuid>9909668a-ced6-4e2a-aee9-55f6f29853f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-77f6703b']/h4</value>
      <webElementGuid>cbd77933-f327-4b6b-81e4-d9a3cd2a026b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WINNER'])[2]/following::h4[1]</value>
      <webElementGuid>7947edbd-5d2e-4982-b25e-bad10006df4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[4]/preceding::h4[1]</value>
      <webElementGuid>7a64399a-fc2a-413e-b53e-dc4b037edd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!']/parent::*</value>
      <webElementGuid>a4cff5db-6a77-4138-a543-39379b6638a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div[2]/div[2]/div/h4</value>
      <webElementGuid>95b165a0-f1b9-45b9-a3c6-32be4a5875e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!' or . = 'Hop into intense player vs player battles with up to 5 other players! Get the highest score to walk away with the entire pot!')]</value>
      <webElementGuid>7bfe6d90-aeaf-4a97-a0c0-aeaca1471493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
