<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Sign Up For Free</name>
   <tag></tag>
   <elementGuidId>2c45ff0a-99ed-496a-823e-70b8ea76cb1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-f9c63f29']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.vce-google-fonts-heading-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ad9de667-5d01-4756-85cb-2c8c15dacb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-google-fonts-heading-inner</value>
      <webElementGuid>ebe88ab2-bd8a-40b2-9554-63cda8763b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up For Free</value>
      <webElementGuid>edef8cf4-2e4c-417b-acc9-1a66dfeed79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-f9c63f29&quot;)/h4[@class=&quot;vce-google-fonts-heading-inner&quot;]</value>
      <webElementGuid>4f1cdef9-a8d8-4e48-903d-fcb7c70357e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-f9c63f29']/h4</value>
      <webElementGuid>3fa754b4-50f1-4125-8337-313c81b16f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[3]/following::h4[1]</value>
      <webElementGuid>18cabbc8-5c83-4cde-8eea-4e6ceb38bdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play for fun or for big crypto prizes. Get started on under 60 seconds!'])[1]/following::h4[1]</value>
      <webElementGuid>7a63499b-0d32-47e1-8568-8c49a8c24727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an account in 60 seconds or less'])[1]/preceding::h4[1]</value>
      <webElementGuid>00fd0846-fa89-4aa7-9cc3-2ec157b08da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Your Coins'])[1]/preceding::h4[1]</value>
      <webElementGuid>5b77c251-5011-448f-ac5a-6f13fd2a48d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Up For Free']/parent::*</value>
      <webElementGuid>677f9a18-1436-4acc-89c1-b1d50ff47b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/h4</value>
      <webElementGuid>1d112868-b187-4aee-9267-20290267b2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Sign Up For Free' or . = 'Sign Up For Free')]</value>
      <webElementGuid>0fb44219-487c-41db-9156-9050096de137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
