<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Turn Coins Into Crypto</name>
   <tag></tag>
   <elementGuidId>ffa1ab74-4aaf-4673-87ce-5bd7881fb4c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-3ced8f06']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-3ced8f06 > h4.vce-google-fonts-heading-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d287a7d8-811c-4748-9ae6-c492cae83662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-google-fonts-heading-inner</value>
      <webElementGuid>baacba4f-8a2b-4e40-9d13-0d7d1f84ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Turn Coins Into Crypto</value>
      <webElementGuid>45fb4748-fb13-4826-b4b2-6ba793d5ba16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-3ced8f06&quot;)/h4[@class=&quot;vce-google-fonts-heading-inner&quot;]</value>
      <webElementGuid>90fd2bf3-7676-43d3-957e-e04b09cae763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-3ced8f06']/h4</value>
      <webElementGuid>bd43b10c-8880-4f95-9fc2-5874912a5fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get your FREE Welcome Pack and get playing'])[1]/following::h4[1]</value>
      <webElementGuid>4d81f8ee-684d-4368-8e1d-14706648c440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Your Coins'])[1]/following::h4[1]</value>
      <webElementGuid>35c024d5-9fcb-4014-bd12-780905aa7c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fast and secure withdrawals guaranteed'])[1]/preceding::h4[1]</value>
      <webElementGuid>9b34fa6b-f289-4fd2-8e50-4bba7033c9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Turn Coins Into Crypto']/parent::*</value>
      <webElementGuid>b667064b-4382-442f-b0a0-323b8f62817a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div/h4</value>
      <webElementGuid>7e876e8b-58f6-4e5a-a19a-98bb7b593879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Turn Coins Into Crypto' or . = 'Turn Coins Into Crypto')]</value>
      <webElementGuid>d6468b94-ae95-44cf-9bfb-f061fa008417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
