<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Read More</name>
   <tag></tag>
   <elementGuidId>bd699023-6249-4513-b6f6-297663aa8fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='slider-11-slide-37-layer-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-37-layer-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>8640561c-b8c2-41f5-a57d-3ff5bdf0a986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-37-layer-17</value>
      <webElementGuid>bb08a501-0e74-411c-bebc-cbfe240c1870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-layer sign-up-slider sign-up rev-btn</value>
      <webElementGuid>3f9e7903-51cc-4878-bd50-6e51b15e5a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08c7cb61-7362-4f0b-8fa1-122dc4fa8398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;y:t,t,b,b;yo:540px,570px,70px,90px;</value>
      <webElementGuid>9edf7eb5-2c02-4a81-be81-08bb608769d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>cdb34c1f-63f6-44e3-9a83-325f8af72da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>ff9b9448-4ee9-476d-abf2-ab93e5bf83aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7516c9e6-7a1f-4c98-91b7-7dafd42d3b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2074ccd8-879a-49a0-967a-ea112f784c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>b2225e1c-d353-494c-9db5-c242cf964799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>43954b41-a541-4320-862f-b7f695b4d6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#72b619;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>ce528d01-562f-4af7-a2f8-a382897ca9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>a13ea044-91c0-4979-882f-5f4bfc8a5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:800;</value>
      <webElementGuid>b6f1a07a-cc19-4aab-9835-3f8dfbd92f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:7200;auto:true;</value>
      <webElementGuid>e7804e41-97c9-4a88-8f00-4ebba5e29e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#fff;bgc:#568913;boc:#568913;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>493ee95a-2a9d-4cf7-9d9e-cd09772993a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae18f95e-0ae5-455b-a837-1d7f1389729c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f4a2018-3340-4fdd-966c-ecab9b752750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db934591-ac67-466c-a7e7-afe810e75343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Read More </value>
      <webElementGuid>e3c43456-9937-4d86-b01a-969f95e158c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-37-layer-17&quot;)</value>
      <webElementGuid>dad580f0-b9fe-400a-a099-8ac3c02dc18c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='slider-11-slide-37-layer-17']</value>
      <webElementGuid>9a30f7fe-79ac-45d4-8067-38b14932e9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-column[@id='slider-11-slide-37-layer-4']/rs-layer-wrap[3]/rs-loop-wrap/rs-mask-wrap/h5</value>
      <webElementGuid>cd4ed2bc-e9bd-4fa6-a392-12850cc73757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Free'])[1]/following::h5[2]</value>
      <webElementGuid>f7f26675-5208-48c0-9f79-71eabdf11f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The #1 player vs player crypto action game!'])[1]/preceding::h5[1]</value>
      <webElementGuid>b5ee48a2-2c02-4e7e-90de-3531d64a92fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play for fun or for big crypto prizes. Get started on under 60 seconds!'])[1]/preceding::h5[1]</value>
      <webElementGuid>5541c2ec-0a6e-4898-922d-24d9a964927f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Read More']/parent::*</value>
      <webElementGuid>dd83ee2f-9eb8-443e-83a7-17b30bcefcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-slide[3]/rs-zone/rs-row-wrap/rs-loop-wrap/rs-mask-wrap/rs-row/rs-column-wrap/rs-loop-wrap/rs-mask-wrap/rs-column/rs-layer-wrap[3]/rs-loop-wrap/rs-mask-wrap/h5</value>
      <webElementGuid>c80e225a-8bee-4aa4-a9db-74279211a666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'slider-11-slide-37-layer-17' and (text() = 'Read More ' or . = 'Read More ')]</value>
      <webElementGuid>d8d3b72a-5d12-48b8-a7db-6b3ba6c07f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
