<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Sign Up</name>
   <tag></tag>
   <elementGuidId>a6634dc8-7b9d-4617-bd83-49a13055e06b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='slider-11-slide-36-layer-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-36-layer-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>417c0220-f745-4548-994f-700281d17950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-36-layer-17</value>
      <webElementGuid>66d91ae1-b042-4e74-b457-358d78d35d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-layer sign-up-slider sign-up rev-btn</value>
      <webElementGuid>97a3d886-d5ac-4ca7-abed-60155c6c1732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bd83cfa-56b4-4d96-a2b6-1d6d619c5dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;y:t,t,b,b;yo:540px,570px,70px,90px;</value>
      <webElementGuid>fd784c2b-b069-4845-a94b-d962ce85b758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>148c22e9-20b4-4848-85a0-c6be2954592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>c69e7815-027e-4d95-a06c-010e7924ca34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>567e9f93-472f-4b96-893a-95b45813e4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f056649b-3ba0-4bff-82fa-570158a46f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>e0bfa6b5-e9f8-44a4-8dc4-3ef1721b5268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>d717809c-8877-44ef-93cf-972742af27ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#ce952e;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>cff46b50-c1ce-4443-a8f2-83f4fbffdeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>1c17977a-476e-4223-944d-572067568a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:800;</value>
      <webElementGuid>c5a9b838-9c53-409b-bb9c-00683d34ad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:7200;auto:true;</value>
      <webElementGuid>c0f7eec2-ed5f-4ad1-9c5b-b826fea1d70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#000;bgc:#ddbc35;boc:#ddbc35;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>01a32ca4-c941-4459-bb5b-0809c80b7e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee63b8a4-95eb-4a80-8d90-5536f5418ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6a80b6b-3477-41e7-b1ce-d0ea831ceb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0e68f6d1-421b-4b3b-965e-6dc4459e14a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up </value>
      <webElementGuid>fad977b0-f537-4b8f-a56f-e514ac7d76f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-36-layer-17&quot;)</value>
      <webElementGuid>4e4f9b1c-d8a6-4803-bd15-1a673ddf9c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h5[@id='slider-11-slide-36-layer-17']</value>
      <webElementGuid>d356b4ae-b5b1-4c03-b679-8bd4f99ea53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-column[@id='slider-11-slide-36-layer-12']/rs-layer-wrap[3]/rs-loop-wrap/rs-mask-wrap/h5</value>
      <webElementGuid>58400b4b-8254-4635-aab6-1a6668101cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='instant Coin Pack for Free.'])[1]/following::h5[1]</value>
      <webElementGuid>f13bf326-d7b5-444c-9732-44d1cbda25da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Free'])[1]/preceding::h5[1]</value>
      <webElementGuid>2e7354ca-a138-4b42-899b-5da68bf2d6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-layer-wrap[3]/rs-loop-wrap/rs-mask-wrap/h5</value>
      <webElementGuid>2d4952d8-4bce-438c-8d17-8e1102b11f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[@id = 'slider-11-slide-36-layer-17' and (text() = 'Sign Up ' or . = 'Sign Up ')]</value>
      <webElementGuid>1b1f1d1d-7a31-441e-a5d2-ffd5ccf8c162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
