<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Buy_fas fa-bell</name>
   <tag></tag>
   <elementGuidId>041c7508-72b1-4e9c-981a-d5c5b8dc8a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='notifications-dropdown']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-bell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2b676bca-ed90-42cb-8e74-aec1382e3dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bell</value>
      <webElementGuid>c75e1890-1537-467e-b8ea-a4af1d90e8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notifications-dropdown&quot;)/i[@class=&quot;fas fa-bell&quot;]</value>
      <webElementGuid>ee602a43-c273-41d8-9bac-bb667e5e7268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='notifications-dropdown']/i</value>
      <webElementGuid>53de5cab-7b14-450a-93a4-bf71cbbc327c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>951c859b-00a2-4343-b899-dacc307287df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
