<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , siqiframe, , ))_siqiframe</name>
   <tag></tag>
   <elementGuidId>f98653cc-315f-499a-90c1-3af47612851b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='siqiframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#siqiframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41643145-f984-4e04-868d-327acfe5648c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>siqiframe</value>
      <webElementGuid>2f3a225b-9123-4110-8f6c-c1ef6256a4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SalesIQ Chatwindow</value>
      <webElementGuid>26742e51-f2c1-46e7-9efb-916aac8f1bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>seamless</name>
      <type>Main</type>
      <value>seamless</value>
      <webElementGuid>3feb1804-f238-4b55-a0bb-9a295dcbd2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>460</value>
      <webElementGuid>9a210f9d-c6f1-4647-824c-ff996d50c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bc7916b7-0c04-4435-ad3b-92e9ff423846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>29250bd9-a3f2-4655-ae56-7b3053026f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siqiframe&quot;)</value>
      <webElementGuid>9e125a12-b5b5-4d24-b2e9-9c6c133d837a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='siqiframe']</value>
      <webElementGuid>3fb77e27-165a-4cbd-922e-5a6f23968b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siqcht']/iframe</value>
      <webElementGuid>2a5f67ba-b432-4a2f-be34-e413f515f6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/iframe</value>
      <webElementGuid>71abdb96-b3ae-4ff3-86aa-413478d73883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'siqiframe' and @title = 'SalesIQ Chatwindow']</value>
      <webElementGuid>70455e74-32ea-4f18-89de-fc5780acf504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
