<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__embed-responsive-item</name>
   <tag></tag>
   <elementGuidId>8d0ceef4-6d9c-4158-9d14-4e8f8b00db17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homePlayVideo']/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homePlayVideo > div.modal-dialog.modal-xl > div.modal-content > div.embed-responsive.embed-responsive-16by9 > iframe.embed-responsive-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>33abfc53-aea0-4e78-8d07-ad531a518a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item</value>
      <webElementGuid>00e9c9d4-4d54-4eff-9c78-ce13c443ce24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1</value>
      <webElementGuid>5a0cd734-69c6-461c-b535-198149e121f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePlayVideo&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9&quot;]/iframe[@class=&quot;embed-responsive-item&quot;]</value>
      <webElementGuid>98385b9d-4862-4566-ade2-24efbea14cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de57c14a-0af2-4e4b-a5b0-c4dae33ca7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item</value>
      <webElementGuid>b96fad3b-a315-4519-b98f-d13c2ffcf3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1</value>
      <webElementGuid>a2e67043-f6f9-49f4-8f49-98609cdc2220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePlayVideo&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9&quot;]/iframe[@class=&quot;embed-responsive-item&quot;]</value>
      <webElementGuid>c2dd1b78-2d3f-422d-b098-2b5830cf7b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6f030497-9ec6-40d5-b751-c558b67bd18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item</value>
      <webElementGuid>0cac84d9-ffef-4f70-902c-f26289051065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1</value>
      <webElementGuid>890425b2-e017-4f58-93e8-e05f0c662b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePlayVideo&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9&quot;]/iframe[@class=&quot;embed-responsive-item&quot;]</value>
      <webElementGuid>0d412e7c-20d0-4c8f-9e13-9405dbd390cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homePlayVideo']/div/div/div/iframe</value>
      <webElementGuid>9820550c-46df-47f1-bac5-941855463f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/iframe</value>
      <webElementGuid>c3d18c42-8238-456e-9e7c-83532278b583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1']</value>
      <webElementGuid>b106ce34-16eb-4704-88c4-e0ac09a13684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
