<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a valid email address_visemail</name>
   <tag></tag>
   <elementGuidId>83188356-a6f4-403e-80fb-a25dbef5679b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='visemail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visemail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ef7f958-44b5-479e-bd33-7e93d3072958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dbfa745-e72e-49d5-adb3-112de7a80d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visemail</value>
      <webElementGuid>0c6163eb-c2a2-4ae5-af3b-110a6f6d84c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>siq-input-text-box errfield</value>
      <webElementGuid>8fabb0ae-0562-499e-a07a-2d43ebe4ffdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address (Required)</value>
      <webElementGuid>c1c9cc06-9a2a-4a66-872c-62946a999bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>info</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0de9840d-bf2a-4c91-8e6d-860610f493e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldname</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1329bef8-9d68-4e04-822d-7f58f0dee552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>purpose</name>
      <type>Main</type>
      <value>visitoremail</value>
      <webElementGuid>b6a989e4-1423-425b-b11c-cc7715af03b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>required email charlimit 100</value>
      <webElementGuid>20d833c5-704f-49ef-8212-586bd172a9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>docblur</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ed497506-bfc3-466e-9c3b-70e2f410c4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-valid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd8c7d22-3fac-405f-a1a1-b549b4cccb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visemail&quot;)</value>
      <webElementGuid>f2b38492-e0b6-451c-9e06-9d3dadc891ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>8433bf6a-e345-4f4f-8c76-0706a0533bbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='visemail']</value>
      <webElementGuid>009acbce-2656-405f-b07c-3ec73da6c83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='window-ribbon']/section/div[3]/input</value>
      <webElementGuid>deda6f03-7fd9-4113-b6e3-68478f495f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>662713fe-bb48-43f7-a148-469dd416a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'visemail' and @placeholder = 'Enter your email address (Required)']</value>
      <webElementGuid>ca476e7a-f85e-4f63-bee7-b0ed8a66c39e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
