<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter a valid name_visname</name>
   <tag></tag>
   <elementGuidId>627adea9-1b01-4476-82cf-d40b9b098284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='visname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6974bcf7-6319-46f6-bfb1-5b6288144319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0431baf-87bc-4a6a-968b-f47a100b94dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visname</value>
      <webElementGuid>459031be-8a6b-4656-b783-82b730e080bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your name (Required)</value>
      <webElementGuid>8b980fdb-c626-4c26-93c9-8f8494fcc2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>siq-input-text-box errfield</value>
      <webElementGuid>74ca0411-0994-4cd2-8748-860650e5af35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>docblur</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>2e14777c-8721-4f2a-a4dd-07bb7605b737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>info</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f199a115-4762-4eaa-83b6-a29281ffcb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldname</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>723b7cb9-75c7-4140-8974-b83f507e5a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>purpose</name>
      <type>Main</type>
      <value>visitorname</value>
      <webElementGuid>48b554bb-fd19-4606-b55a-53f40806f79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>required charlimit 100</value>
      <webElementGuid>494908c8-9501-4672-a4fa-36d2f0b8700f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-valid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7145860-56f8-4c6f-808f-b7ba7420a27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visname&quot;)</value>
      <webElementGuid>88d710fc-843f-44ce-a369-347570f10f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>a4ea0f19-38de-4fd9-a16a-24bd89db0d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='visname']</value>
      <webElementGuid>413133a3-95e6-41d2-88fb-a8c392e7e7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='window-ribbon']/section/div[2]/input</value>
      <webElementGuid>e983ced3-bc7c-49e2-801f-484b4958f95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b84cf7f8-a33b-4878-a0ef-a8763a4dc2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'visname' and @placeholder = 'Enter your name (Required)']</value>
      <webElementGuid>a8e5eb8b-44e4-4745-b968-78e5155b17d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
