<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email is not valid_forgotPasswordButton</name>
   <tag></tag>
   <elementGuidId>d131f75a-e209-4f4a-9eac-c3d923af93df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='forgotPasswordButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;forgotPasswordButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b0295df-9023-42bc-baba-cebfe438ee47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn</value>
      <webElementGuid>a742cb2e-eb4b-4f8c-805a-3872c7586e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>forgotPasswordButton</value>
      <webElementGuid>bbdc48d5-835a-4be7-8a37-633028b87c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4b7e43b4-f498-4d73-b60c-6f251a71b45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset Password</value>
      <webElementGuid>a2e4d1b7-b907-432e-8b63-05bb775568b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalForgotPassword&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;btn-wrap text-center&quot;]/input[@class=&quot;submit-btn&quot;]</value>
      <webElementGuid>51b748b9-db88-4534-a34e-134543e8c4ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='forgotPasswordButton']</value>
      <webElementGuid>4b756249-774f-4bb3-9b27-c3468aaa57a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalForgotPassword']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>09e50933-217c-4d34-81f1-29a550d89876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>ad196da1-fcdd-4097-8be8-32195ac44a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'forgotPasswordButton' and @type = 'submit']</value>
      <webElementGuid>b7677d89-a969-48c7-9f1b-d04423bd6082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
