<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Yes, Im over 21 and I agree to the Te_6a71bc</name>
   <tag></tag>
   <elementGuidId>c1228d03-9074-4a7c-889e-9ba991f71a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalRegister']/div/div/div[2]/form/div[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3070435e-5424-47d2-abf6-56421096b8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>over18</value>
      <webElementGuid>8279d9c3-8d22-4788-998d-894abe68bcce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes, I'm over 21 and I agree to the Terms &amp; Conditions and Privacy Policy.</value>
      <webElementGuid>2ff924c8-26fe-44b5-8cc2-3825f8c96690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalRegister&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;checkbox&quot;]/label[1]</value>
      <webElementGuid>9328f3ba-b5dd-43ba-906f-250072f1b6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c26fc834-72f7-495b-9ab3-fcb36e91e83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>over18</value>
      <webElementGuid>828378da-dad2-46ed-b193-3c42bf3188e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes, I'm over 21 and I agree to the Terms &amp; Conditions and Privacy Policy.</value>
      <webElementGuid>46e2ad85-716f-43e8-87fa-f07361a37f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalRegister&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;checkbox&quot;]/label[1]</value>
      <webElementGuid>f8a7070d-f624-4a82-8114-faf6ba94eed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b4e43f94-90f4-4d79-9710-67df533a4273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>over18</value>
      <webElementGuid>3341acd0-68f9-453c-ae70-bec7f0a83cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes, I'm over 21 and I agree to the Terms &amp; Conditions and Privacy Policy.</value>
      <webElementGuid>b8cc264d-74dd-48e2-82f2-61a725ba41c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalRegister&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[@class=&quot;checkbox&quot;]/label[1]</value>
      <webElementGuid>16c4721a-101f-4c82-93cc-355785499c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalRegister']/div/div/div[2]/form/div[4]/label</value>
      <webElementGuid>fbe49738-bf3c-4ff3-825c-c071185050c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please use 6-16 characters, including at least 1 number, 1 letter and 1 special character -!@$^&amp;*'])[1]/following::label[1]</value>
      <webElementGuid>8fbfdd82-0605-45e9-8796-920b7b7e6bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username is not valid.'])[1]/following::label[1]</value>
      <webElementGuid>9d26268c-7b26-4094-a418-a5dfb12d6327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c8bc42ea-ef3a-4f43-ac8d-a4e5a97789cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = concat(&quot; Yes, I&quot; , &quot;'&quot; , &quot;m over 21 and I agree to the Terms &amp; Conditions and Privacy Policy.&quot;) or . = concat(&quot; Yes, I&quot; , &quot;'&quot; , &quot;m over 21 and I agree to the Terms &amp; Conditions and Privacy Policy.&quot;))]</value>
      <webElementGuid>aa6253d8-89b3-42f8-a6a6-adc423ec899e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
