<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_From the dangerous depths of the Amazonia_3ca983</name>
   <tag></tag>
   <elementGuidId>5dfbb5f1-4692-4bdd-9d62-f4923bd4411f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-79e143a3']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-79e143a3 > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d0d016ca-67ef-43ec-a27b-f6c6798c0998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>52756bfb-32d6-4b2c-a1c6-2f1fee9abc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>fce46192-ba0f-422c-bb21-ec855bc051e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>713f3596-7836-404c-a4d9-3c1750031402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>f9f79217-dee7-49e3-b690-9162cd3ba86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>82e18608-2955-48f4-bf6e-b25866cc6ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>336e292c-1616-4756-9d1d-4dd3fb96c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>73b3c812-6abf-4841-83e7-3d69e877818b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>d5446484-b842-4ec7-9254-8720c1863ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>acc04d41-59a9-431e-91c7-0771e7994403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>9e11bebb-ad80-4224-9c09-b15d12e02340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>271ba6ed-b048-4006-99bc-b60d346d1a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>337d767f-573a-4b00-ac55-427cc26d8f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>a7d59870-7293-4e49-b9a9-a1887d331418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>d42d4191-35c2-40c6-b04e-c91b6d5c76a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>34392d06-cfac-4b5e-904c-0ae0d8647e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>d1a1ab55-614e-4e25-9be5-849ef7af5122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>8b832aa9-c8df-4cc8-bb56-546961e9b8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>215c54b5-b32e-4865-a81b-43bce56d5e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>4b5e45ee-e361-41de-87cb-af208b0ae468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>8fb8f51e-4569-4e0e-acde-61b7147c99d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1405c350-6a52-4714-a261-6e21a7a36b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? </value>
      <webElementGuid>921236d7-aa43-436b-b645-c2db8c551a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-79e143a3&quot;)/p[1]</value>
      <webElementGuid>655f9439-4468-45e6-8aee-b86024042cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-79e143a3']/p</value>
      <webElementGuid>c27bf04e-9d42-4cdf-8d57-805bf6902bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Worlds'])[1]/following::p[1]</value>
      <webElementGuid>c3089ff5-5a18-4304-9741-a924bb6994e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[2]/preceding::p[1]</value>
      <webElementGuid>e8db36a5-4f2f-40b0-a10b-234ed360a1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose from Slots, Blackjack, Roulette and much more - no purchase required!'])[1]/preceding::p[1]</value>
      <webElementGuid>c7345d73-ee9c-4b46-89eb-e916a2cb226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='From the dangerous depths of the Amazonian Jungle to']/parent::*</value>
      <webElementGuid>4d416dd6-2e45-4943-8779-0f418da25b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/div/div/div/p</value>
      <webElementGuid>3fe53916-a224-4916-894f-35b6cfcc2bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? ' or . = 'From the dangerous depths of the Amazonian Jungle tothe forgotten realm of the Black Dragon – we’ve got you covered. Where will you go today? ')]</value>
      <webElementGuid>04b694eb-17b4-4c6f-8cf1-42eb648aaec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
