<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-bullet_WINNER_tp-bullet rs-touchhover</name>
   <tag></tag>
   <elementGuidId>cfd37f72-da88-4ea8-9d62-4a732d74def2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rs-module[@id='rev_slider_11_1']/rs-bullets/rs-bullet[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>rs-bullet.tp-bullet.rs-touchhover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-bullet</value>
      <webElementGuid>1e7c9672-ff07-4bf0-a565-b5bb4023e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>rs-36</value>
      <webElementGuid>abf6304c-83c3-4575-b555-c0535f1ad8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-bullet rs-touchhover</value>
      <webElementGuid>5f0147eb-9701-4cd8-ae9b-9d23946a916b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rev_slider_11_1&quot;)/rs-bullets[@class=&quot;tp-bullets hesperiden horizontal nav-pos-hor-center nav-pos-ver-bottom nav-dir-horizontal rs-touchhover&quot;]/rs-bullet[@class=&quot;tp-bullet rs-touchhover&quot;]</value>
      <webElementGuid>b86028b0-555e-4b88-9095-449c6db44dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-bullet</value>
      <webElementGuid>dff2c6bb-7de2-4246-b933-9a53c57d1782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>rs-36</value>
      <webElementGuid>d04da021-deee-4f43-91b1-663e8c27cdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-bullet rs-touchhover</value>
      <webElementGuid>e8bfda27-eeb4-4aec-a293-1fbc2328c2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rev_slider_11_1&quot;)/rs-bullets[@class=&quot;tp-bullets hesperiden horizontal nav-pos-hor-center nav-pos-ver-bottom nav-dir-horizontal rs-touchhover&quot;]/rs-bullet[@class=&quot;tp-bullet rs-touchhover&quot;]</value>
      <webElementGuid>ef68a41b-b86d-44ae-b1a9-060f0894ac4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-bullet</value>
      <webElementGuid>b416836f-b80f-4d9c-a297-d08e7f3ae9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>rs-34</value>
      <webElementGuid>7c01b90b-f103-489b-984b-516dcc35543e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-bullet rs-touchhover</value>
      <webElementGuid>d33dfdac-21a8-4ad3-b31e-e479fc0133b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rev_slider_11_1&quot;)/rs-bullets[@class=&quot;tp-bullets hesperiden horizontal nav-pos-hor-center nav-pos-ver-bottom nav-dir-horizontal rs-touchhover&quot;]/rs-bullet[@class=&quot;tp-bullet rs-touchhover&quot;]</value>
      <webElementGuid>7d033ef9-db55-4b57-a4c9-931ed7d18a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-bullet</value>
      <webElementGuid>340537bb-2ba8-4d79-9b6a-42bc5d392df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>rs-34</value>
      <webElementGuid>df9a9e32-f43f-4dd1-9826-685f8bcfe30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-bullet rs-touchhover</value>
      <webElementGuid>c2bb0e53-a49c-4245-9ec2-9c2e82c9b6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rev_slider_11_1&quot;)/rs-bullets[@class=&quot;tp-bullets hesperiden horizontal nav-pos-hor-center nav-pos-ver-bottom nav-dir-horizontal rs-touchhover&quot;]/rs-bullet[@class=&quot;tp-bullet rs-touchhover&quot;]</value>
      <webElementGuid>e404cf17-080d-4be0-9331-f1b016e3a745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-module[@id='rev_slider_11_1']/rs-bullets/rs-bullet[2]</value>
      <webElementGuid>67ee17fe-086d-4595-8181-3813e5504fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-bullet[2]</value>
      <webElementGuid>c356bf4b-7737-4d94-a8e4-3ec190db9acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-module[@id='rev_slider_11_1']/rs-bullets/rs-bullet</value>
      <webElementGuid>c12aa863-c924-443d-a0b9-18893e27a8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-bullet</value>
      <webElementGuid>7ffc214a-75a6-4475-bd41-4e0072614694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
