<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-column-bg_Sign Up_slider-11-slide-34-lay_b23b76</name>
   <tag></tag>
   <elementGuidId>6f0c1ca8-b0d2-4cee-acdd-3ca18079da15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rs-column-bg[@id='slider-11-slide-34-layer-16_rs_cbg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-34-layer-16_rs_cbg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-column-bg</value>
      <webElementGuid>83860790-f7cc-4796-8a2a-654a4a6e3989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-34-layer-16_rs_cbg</value>
      <webElementGuid>84b8fba2-0326-4743-9724-6f9676bb8bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-34-layer-16_rs_cbg&quot;)</value>
      <webElementGuid>59d34687-8d71-44a1-96a9-58d73e6926dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rs-column-bg[@id='slider-11-slide-34-layer-16_rs_cbg']</value>
      <webElementGuid>61aa4150-eb63-49ce-9200-dbbbfd305860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-row[@id='slider-11-slide-34-layer-13']/rs-column-wrap/rs-cbg-mask-wrap/rs-column-bg</value>
      <webElementGuid>525fd698-f6c3-4ec9-b532-7fded2913953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-column-bg</value>
      <webElementGuid>6adef153-27c9-41eb-ae54-6d09553711c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rs-column-bg[@id = 'slider-11-slide-34-layer-16_rs_cbg']</value>
      <webElementGuid>29ace437-5afc-46eb-a0cb-34a0c74de363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
