<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-column-bg_Read More_slider-11-slide-37-l_1a9f45</name>
   <tag></tag>
   <elementGuidId>0f83bfac-e496-4e36-98d6-3520eeeadc2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rs-column-bg[@id='slider-11-slide-37-layer-4_rs_cbg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-37-layer-4_rs_cbg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-column-bg</value>
      <webElementGuid>87da7469-a16e-4f59-b30e-c7da5b356482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-37-layer-4_rs_cbg</value>
      <webElementGuid>0e35972b-b284-4891-8f0e-4658d5170aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-37-layer-4_rs_cbg&quot;)</value>
      <webElementGuid>71e8fc0b-5c39-4cdb-9356-9d8704577da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rs-column-bg[@id='slider-11-slide-37-layer-4_rs_cbg']</value>
      <webElementGuid>f278c691-7bc5-475a-adb2-648c9b93145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-row[@id='slider-11-slide-37-layer-0']/rs-column-wrap/rs-cbg-mask-wrap/rs-column-bg</value>
      <webElementGuid>8a4f9290-a3ee-44ca-aa8d-081ecac6b3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-slide[3]/rs-zone/rs-row-wrap/rs-loop-wrap/rs-mask-wrap/rs-row/rs-column-wrap/rs-cbg-mask-wrap/rs-column-bg</value>
      <webElementGuid>8ebdc201-96fd-4e7f-b0ca-4c6ed8f4758b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rs-column-bg[@id = 'slider-11-slide-37-layer-4_rs_cbg']</value>
      <webElementGuid>dbdb43dd-004e-4a16-a777-087f89cb730e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
