<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-column_Sign up today For 50,000 Quest Co_04a936</name>
   <tag></tag>
   <elementGuidId>12a6a95f-9d9f-4aa1-baf2-380ab633aef8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-36-layer-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-column</value>
      <webElementGuid>12f7ec2b-f3f8-47c9-b83a-3177e0dff14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-36-layer-12</value>
      <webElementGuid>919f3db1-fd13-4271-b9f2-9f139e79d71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>column</value>
      <webElementGuid>34b63459-55da-4548-911b-9b97aa997209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>xo:50px;yo:50px;</value>
      <webElementGuid>ce8d2eb3-3c8a-4a2a-a564-20fcb53a5cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>a:left,center,center,center;</value>
      <webElementGuid>510c76d2-db4c-48d3-b81e-422fc6dc22e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a3b09bb-29ff-44fb-84fe-db01bb707f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column</name>
      <type>Main</type>
      <value>w:100%;a:bottom;</value>
      <webElementGuid>ba834207-789f-4420-afce-fbe8f7530944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-padding</name>
      <type>Main</type>
      <value>t:10;r:10;b:10;l:10;</value>
      <webElementGuid>1c6501a8-321b-4f80-82f7-80ba5ddb519b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>o:1;</value>
      <webElementGuid>a12a41d1-eeee-4031-9687-347411ffa64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>o:0;st:w;sA:9000;</value>
      <webElementGuid>574e30d9-e68d-4f8b-ba9f-54c43d0f6a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rs-layer</value>
      <webElementGuid>0c705e2c-450c-457c-a65a-41a4758123bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>044befeb-4010-4fd2-9fcd-e00204c2fcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e83e4f9-0a15-4b9b-94cd-4489b5934abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc883fdd-28f1-46cb-8099-79727e5aba41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                       Sign up today For 50,000 Quest Coins and 5 Max Coins 
                       Create an account for an instant Coin Pack for Free.  No purchase necessary! 
                       Sign Up 
                      </value>
      <webElementGuid>644650e2-60cc-4fe3-9f87-d65427d054ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-36-layer-12&quot;)</value>
      <webElementGuid>0fe1d3bb-0b47-4c30-a8b7-a7a42e25eb3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rs-column[@id='slider-11-slide-36-layer-12']</value>
      <webElementGuid>11a248c8-e390-412d-a74e-a0289b18b63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-row[@id='slider-11-slide-36-layer-6']/rs-column-wrap/rs-loop-wrap/rs-mask-wrap/rs-column</value>
      <webElementGuid>71e2ac25-130d-48ab-8045-38efbdf2f62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::rs-column[1]</value>
      <webElementGuid>603e693b-5139-43cc-86bf-7c465f74ff04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch Trailer'])[1]/following::rs-column[1]</value>
      <webElementGuid>3c29fd80-9d4c-44e5-b348-f489e816fc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-slide[2]/rs-zone/rs-row-wrap/rs-loop-wrap/rs-mask-wrap/rs-row/rs-column-wrap/rs-loop-wrap/rs-mask-wrap/rs-column</value>
      <webElementGuid>6e358576-c900-4ad0-ab8c-9e3f74cda340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rs-column[@id = 'slider-11-slide-36-layer-12' and (text() = '
                       Sign up today For 50,000 Quest Coins and 5 Max Coins 
                       Create an account for an instant Coin Pack for Free.  No purchase necessary! 
                       Sign Up 
                      ' or . = '
                       Sign up today For 50,000 Quest Coins and 5 Max Coins 
                       Create an account for an instant Coin Pack for Free.  No purchase necessary! 
                       Sign Up 
                      ')]</value>
      <webElementGuid>be9e71a9-7ff5-44e2-9da0-131611757225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
