<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-layer_Watch Trailer</name>
   <tag></tag>
   <elementGuidId>00aa21b6-821e-4707-8991-0405b4b57cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rs-layer[@id='slider-11-slide-34-layer-9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-34-layer-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-layer</value>
      <webElementGuid>e586ca2e-6210-4781-bf2c-b10abd962068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-34-layer-9</value>
      <webElementGuid>8039e4b9-71dd-4d80-bdb4-39a6fcfb49a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rev-btn rs-layer rs-waction rs-wclickaction</value>
      <webElementGuid>3e4b6a18-cfe6-4d8f-a981-10f5165b765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78851b59-89bc-452f-8b59-4bee55aba252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;xo:-180px,-180px,-160px,0;y:t,t,b,b;yo:540px,570px,70px,170px;</value>
      <webElementGuid>2a3c04df-4870-49d5-b5fe-63abd34c7c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>49fbd74a-01ce-4753-9c34-f97d67716eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>80885ea8-e3f9-4bb3-af12-5178df538243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions</name>
      <type>Main</type>
      <value>o:click;a:callback;call:$(&quot;#homePlayVideo iframe&quot;).attr(&quot;src&quot;, &quot;https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1&quot;), $(&quot;#homePlayVideo&quot;) .modal(&quot;show&quot;);</value>
      <webElementGuid>c4bcb230-b00d-49c9-b841-68227d9acb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9169bfe6-5396-4f6e-b007-24e247654fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8901f1a4-281a-46ad-a70e-45fafdce88ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>fa97dba1-bc60-463f-8d34-c75ee462ecd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>930f9074-2de6-4374-a6fd-bac8d2b1ec32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#ffffff;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>9bdb481e-7a66-461f-829c-63c16809b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>a8276712-0b0b-4a61-a008-61afd7b55b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:500;</value>
      <webElementGuid>6a89bf03-0657-4a3d-b90c-b02db4092c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:8000;auto:true;</value>
      <webElementGuid>29af3647-e80b-4d29-ad2f-7c825916e791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#56469d;bgc:#fff;boc:#56469d;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>88dcd857-0b80-4a36-a867-37870e035b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e367af1f-0fca-4c8e-a642-dce03adad561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37ecd1d1-87d8-445c-a253-32374650ac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a385bc72-cfd7-4d04-9227-882135d02d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Watch Trailer 
                         
                       </value>
      <webElementGuid>bae6fd5f-6c5d-4d03-9d68-d506bf0b6052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-34-layer-9&quot;)</value>
      <webElementGuid>61467f9a-fd2c-48af-a9da-3c1eccb79759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-layer</value>
      <webElementGuid>faa76fe6-b120-475f-8e4e-d62ba1f7365c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-34-layer-9</value>
      <webElementGuid>0e3059c8-c564-4aa3-b3e9-06c3eabd381c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rev-btn rs-layer rs-waction rs-wclickaction</value>
      <webElementGuid>7f8c974d-f515-4e14-a774-b5d1c71509ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd7b7d39-055d-4cbd-954c-7b80c71b83ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;xo:-180px,-180px,-160px,0;y:t,t,b,b;yo:540px,570px,70px,170px;</value>
      <webElementGuid>6973421f-d6df-49c6-9109-e80b292975b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>ee8f23a1-f347-4827-a333-71992dec9720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>7ce553b4-6650-4e57-a19a-8e04dc05da53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions</name>
      <type>Main</type>
      <value>o:click;a:callback;call:$(&quot;#homePlayVideo iframe&quot;).attr(&quot;src&quot;, &quot;https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1&quot;), $(&quot;#homePlayVideo&quot;) .modal(&quot;show&quot;);</value>
      <webElementGuid>7690cf44-18ca-4ef0-8ea0-5e4402a4d38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ffefd718-dc72-4f2b-8ab1-74705389ee7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bbbb3f38-dbee-4dd9-ad8b-e3ad49f624d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>ff31ab83-46d7-40ed-9cee-2f6c69f61f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>97d9413e-a750-4fcb-a5e6-6e469ff870bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#ffffff;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>07be7951-d317-42a0-a4e8-feff6d16bf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>795a4049-78ca-45a7-93f9-39da0f878a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:500;</value>
      <webElementGuid>ad7d2823-b850-4ddf-8126-111534495753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:8000;auto:true;</value>
      <webElementGuid>a9bb7c45-b012-4e47-94e2-fd92e72ea69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#56469d;bgc:#fff;boc:#56469d;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>bee32039-3b87-4afc-ac3f-6e001ece0f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56edcffe-7567-40dd-8b51-ea97f3059158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2c3f031-d172-4923-9d13-f7dba9826296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e986f89-49cd-404c-9703-0cf79b02dee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Watch Trailer 
                         
                       </value>
      <webElementGuid>33bc4e1c-7389-4479-8753-0f302d186906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-34-layer-9&quot;)</value>
      <webElementGuid>e96d0a1f-9095-4340-93a8-d65ac7c0187f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-layer</value>
      <webElementGuid>5c2c2d5c-3f77-4be8-acce-d256f96583af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-34-layer-9</value>
      <webElementGuid>b7607e16-3164-46a0-8872-a613dce0dfbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rev-btn rs-layer rs-waction rs-wclickaction</value>
      <webElementGuid>ddb46a70-15e9-4268-b7c9-577b980294cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e7ff6f3-f00b-4d38-9149-06a253f4683c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;xo:-180px,-180px,-160px,0;y:t,t,b,b;yo:540px,570px,70px,170px;</value>
      <webElementGuid>f4a44cec-a6ae-4d50-99d2-e13bcde74c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>76f2bb17-f919-443c-abc1-cda43b61d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>8817f96e-a174-4eb9-807b-8d6232ecda74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-actions</name>
      <type>Main</type>
      <value>o:click;a:callback;call:$(&quot;#homePlayVideo iframe&quot;).attr(&quot;src&quot;, &quot;https://www.youtube.com/embed/4_pnqG7reLE?color=red&amp;showinfo=0&amp;loop=0&amp;rel=0&amp;start=0&amp;cc_load_policy=0&amp;iv_load_policy=3&amp;enablejsapi=1&quot;), $(&quot;#homePlayVideo&quot;) .modal(&quot;show&quot;);</value>
      <webElementGuid>9c432675-5b2d-4c5f-ac0b-ecaadd09c849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7a6e2f64-ae13-4941-b1aa-51845f892c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>469ab0fc-fec1-4279-9f68-2d99b04a94cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>9512b56e-07ce-4a1f-9081-18a893c01d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>263cfae9-2e89-42f6-b16e-477d9cba4b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#ffffff;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>b15ba690-14d9-43d4-87a8-5e9fae63b3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>ef8f54e3-bfde-46dc-bd5e-2f0337a169a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:500;</value>
      <webElementGuid>e8263f44-6071-42ec-89f1-294bd7bf941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:8000;auto:true;</value>
      <webElementGuid>cad7ccdb-ed3b-4d5a-9024-256e4ef37f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#56469d;bgc:#fff;boc:#56469d;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>ab54d8ce-cdb9-43aa-bc69-4c503859ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>187c294a-8e28-4462-b81c-2d6a84dc802e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7ebc37c-e0c5-497a-96e5-0751c5f88500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7d95e4f-e457-4150-a974-6c78177d9429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Watch Trailer 
                         
                       </value>
      <webElementGuid>93780b92-66c7-4f08-b9cb-a91f549e9738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-34-layer-9&quot;)</value>
      <webElementGuid>3376609e-c575-4024-873a-7bc372478f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rs-layer[@id='slider-11-slide-34-layer-9']</value>
      <webElementGuid>34d62436-c411-4a9e-babc-90fe4dd750e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-column[@id='slider-11-slide-34-layer-16']/rs-layer-wrap[3]/rs-loop-wrap/rs-mask-wrap/rs-layer</value>
      <webElementGuid>48a6741c-6190-4916-8208-81f0bb0646f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play for fun or for big crypto prizes. Get started in under 60 seconds!'])[1]/following::rs-layer[1]</value>
      <webElementGuid>7670d124-9fd8-4e5b-a2b2-f6d781fd3c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::rs-layer[1]</value>
      <webElementGuid>4b66aece-40a5-4c42-baf8-c3387200d89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watch Trailer']/parent::*</value>
      <webElementGuid>4870d283-8f5b-4bb8-a05c-6450381bd4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-layer</value>
      <webElementGuid>1683b217-a1ab-40b6-a65c-6a1dc7e6e8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rs-layer[@id = 'slider-11-slide-34-layer-9' and (text() = '
                        Watch Trailer 
                         
                       ' or . = '
                        Watch Trailer 
                         
                       ')]</value>
      <webElementGuid>7ed8d046-23c9-43c0-af76-3925abcb7752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
