<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs-layer_Sign Up</name>
   <tag></tag>
   <elementGuidId>d38be3f7-38ea-4149-a011-734b4791f8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//rs-layer[@id='slider-11-slide-34-layer-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slider-11-slide-34-layer-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rs-layer</value>
      <webElementGuid>0e7336f9-b967-402e-be46-4ccbe611172f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider-11-slide-34-layer-17</value>
      <webElementGuid>e596ce92-8c1f-4af1-8952-c0fa740adaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-up-slider sign-up rev-btn rs-layer</value>
      <webElementGuid>4a6ec4f7-6b81-49ee-8213-28ce413d37ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13851fcf-c13d-4ba5-b144-d556bce08913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-xy</name>
      <type>Main</type>
      <value>x:c;xo:180px,180px,160px,0;y:t,t,b,b;yo:540px,570px,70px,100px;</value>
      <webElementGuid>aa7ff8a9-f2b8-4cc2-94ba-8e092311cff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text</name>
      <type>Main</type>
      <value>w:normal;s:24,24,20,18;l:54,54,54,47;ls:1px,1px,2px,2px;fw:600,600,600,700;a:center;</value>
      <webElementGuid>0d915ab5-7487-48d7-bba0-452f208f61c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dim</name>
      <type>Main</type>
      <value>w:350px,350px,300px,250px;</value>
      <webElementGuid>dd73a1a2-6ddd-4ca9-9ac0-e17ab788cd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_o</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5d4a50f6-8f84-4fb1-82e1-40e6cfbe5102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rsp_bd</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ebfae3a8-69fa-4797-a040-e3300588c9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disp</name>
      <type>Main</type>
      <value>inline-block</value>
      <webElementGuid>ebdd4d94-9c8c-42a2-b851-0b2890513f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-margin</name>
      <type>Main</type>
      <value>r:10;b:10;l:10;</value>
      <webElementGuid>aef1052d-06df-4f00-958d-85a8ad912e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-border</name>
      <type>Main</type>
      <value>bos:solid;boc:#ce952e;bow:3px,3px,3px,3px;bor:30px,30px,30px,30px;</value>
      <webElementGuid>1e923442-cc22-4e1f-bc92-d60bd26c1fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_0</name>
      <type>Main</type>
      <value>y:50px;blu:10px;</value>
      <webElementGuid>2af4b46b-463b-42bb-8d22-3046a183ac39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_1</name>
      <type>Main</type>
      <value>st:400;sp:500;sR:500;</value>
      <webElementGuid>ae91b75f-e642-4840-83d2-af5b6cd8341d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_999</name>
      <type>Main</type>
      <value>st:w;sp:600;sR:8000;auto:true;</value>
      <webElementGuid>4472c32a-c72e-4d1e-90bf-117e857ab2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frame_hover</name>
      <type>Main</type>
      <value>c:#000;bgc:#ddbc35;boc:#ddbc35;bor:30px,30px,30px,30px;bos:solid;bow:3px,3px,3px,3px;oX:50;oY:50;sp:200;e:power1.inOut;</value>
      <webElementGuid>09c9f9da-285a-47ee-9586-96bdb9a51f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21a5124c-146a-4c33-b1de-cf9739cbf436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stylerecorder</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be48fba4-8ca0-400c-bc20-4fd297be2a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialised</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9321730-13d6-471d-a6af-765407d74356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Sign Up 
                       </value>
      <webElementGuid>f268cd6f-0d05-47e0-bd8c-d342b95f82b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider-11-slide-34-layer-17&quot;)</value>
      <webElementGuid>4d92d495-c0b5-4993-868a-6825d3a54297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//rs-layer[@id='slider-11-slide-34-layer-17']</value>
      <webElementGuid>07e11ba3-abdb-46eb-9eba-f186e0b18ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//rs-column[@id='slider-11-slide-34-layer-16']/rs-layer-wrap[4]/rs-loop-wrap/rs-mask-wrap/rs-layer</value>
      <webElementGuid>f340f4f6-0e1d-48d5-88d5-a9448717e88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch Trailer'])[1]/following::rs-layer[1]</value>
      <webElementGuid>44dd14de-ae01-4dd4-ba3d-805e63fdf783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play for fun or for big crypto prizes. Get started in under 60 seconds!'])[1]/following::rs-layer[2]</value>
      <webElementGuid>188a47a0-4fa3-4f5d-b5ed-9af2259e2f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up today'])[1]/preceding::rs-layer[3]</value>
      <webElementGuid>f7fb9214-effb-44a2-ac52-33269e522aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Up']/parent::*</value>
      <webElementGuid>3fb61171-129b-445c-81b9-455b59ab368a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//rs-layer-wrap[4]/rs-loop-wrap/rs-mask-wrap/rs-layer</value>
      <webElementGuid>ef5b4395-d2ec-4e5b-bf27-ef21656e00c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//rs-layer[@id = 'slider-11-slide-34-layer-17' and (text() = '
                        Sign Up 
                       ' or . = '
                        Sign Up 
                       ')]</value>
      <webElementGuid>6983258b-18f5-4699-9fc2-7de8696dd986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
