<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rewards</name>
   <tag></tag>
   <elementGuidId>1971186f-a866-4e86-a68a-04d879d7f593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-a36eb605']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-a36eb605 > h1 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6090f6ee-d9b1-4761-bd51-6cad14cb7b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rewards</value>
      <webElementGuid>842c6985-d3e7-4027-9f1d-8964fd374113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-a36eb605&quot;)/h1[1]/span[1]</value>
      <webElementGuid>344c5b45-ac44-495b-bd1f-cff932eacccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-a36eb605']/h1/span</value>
      <webElementGuid>4c64706b-263b-4f79-8880-470912903208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[4]/following::span[1]</value>
      <webElementGuid>f0e0d03f-5e40-4eaa-a08a-3aad666a83fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[5]/preceding::span[1]</value>
      <webElementGuid>6e8c233d-027b-468f-aa0d-ce9b9cb36270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rewards']/parent::*</value>
      <webElementGuid>80adea13-f9a6-4722-8ce0-1722c62640c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div[2]/div/div/h1/span</value>
      <webElementGuid>a0b91ddb-ba91-4b3c-91de-d8a0bffea6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rewards' or . = 'Rewards')]</value>
      <webElementGuid>966cd156-7f72-42d6-b9e5-50461f476ed5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
