<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toggle navigation_icon-bar</name>
   <tag></tag>
   <elementGuidId>99b81ce8-7706-4a93-8e0f-bf4380889fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div[2]/div/div/div/button/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93c90ac5-d0b1-48bf-9b73-3a9339f8d86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bar</value>
      <webElementGuid>e83487c5-4216-45b9-91e3-d8f256296f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar fixed&quot;]/div[@class=&quot;header-navbar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;navbar-wrapper clearfix&quot;]/div[@class=&quot;navbar-header&quot;]/button[@class=&quot;navbar-toggle&quot;]/span[@class=&quot;icon-bar&quot;]</value>
      <webElementGuid>ab7f6778-fb03-42ae-871b-84d0e4a07bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div[2]/div/div/div/button/span[3]</value>
      <webElementGuid>5e86040d-06d4-45a5-ae7d-724da4357c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>7ceb5bd5-a83a-455f-a7a9-b28c80c0338f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
