<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Crypto_fab fa-tiktok</name>
   <tag></tag>
   <elementGuidId>130efd48-3a9b-4119-834e-a55cf388c8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer']/div/div/div/div[2]/ul/li[5]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fab.fa-tiktok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab331e79-f328-475e-8480-9f48861af734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fab fa-tiktok</value>
      <webElementGuid>d9aefac5-6e92-43b7-a134-bd3c65e4dbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;footer-bottom&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;footer-left-block&quot;]/div[@class=&quot;footer-socials&quot;]/ul[1]/li[5]/a[1]/span[@class=&quot;fab fa-tiktok&quot;]</value>
      <webElementGuid>534d5baf-ef65-4845-b8d5-28c9313ff594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div/div/div/div[2]/ul/li[5]/a/span</value>
      <webElementGuid>88ac4571-e53e-4c6d-b861-ad290c908da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>2b2ec7a9-6966-4599-9f17-5a1914696cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
