<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_QC 70,000.00_slider</name>
   <tag></tag>
   <elementGuidId>b67446d6-425b-4b0a-af20-3caaafcb691e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/div/div/div[2]/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a7dc29f-1fce-44cc-9b89-3e41869562f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>7d9610b6-7657-431c-b91f-ac8cd2a9c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar fixed&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;user-menu-section-wrapper&quot;]/div[@class=&quot;user-menu-section&quot;]/div[@class=&quot;toggle-bar&quot;]/label[@class=&quot;switch&quot;]/span[@class=&quot;slider&quot;]</value>
      <webElementGuid>dde79264-3f22-4ef1-927d-f29db37e3176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f9910c2-62a4-4962-a02e-daca2a73793d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>a2805631-c3d9-4835-80a9-6a4468fde8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;navbar fixed&quot;]/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;user-menu-section-wrapper&quot;]/div[@class=&quot;user-menu-section&quot;]/div[@class=&quot;toggle-bar&quot;]/label[@class=&quot;switch&quot;]/span[@class=&quot;slider&quot;]</value>
      <webElementGuid>8aface1d-f5d8-430b-84f1-75a280c2ec16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div/div/div[2]/div/div/label/span</value>
      <webElementGuid>68e7b18c-60a4-4350-a6a1-0bfe95933b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>879ac573-7f20-4dd9-baa8-3b3d6a9f8b77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
