<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_THIS IS A TEST MESSAGE IGNORE IT P_7d0081</name>
   <tag></tag>
   <elementGuidId>fca763f5-291c-4f50-9693-fc28f3540951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='msgarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msgarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>73c4f91b-d297-43f3-b529-c794128a8610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your message and hit Enter</value>
      <webElementGuid>8db71450-30a6-4cf2-9d4b-3ab837a4c95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msgarea siq-message-textarea</value>
      <webElementGuid>83d43269-ff63-46c5-8d83-5f3b6fe493fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msgarea</value>
      <webElementGuid>b498a56c-37fa-47e7-a836-c262f720160d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>proptype</name>
      <type>Main</type>
      <value>msgarea</value>
      <webElementGuid>b262d0cc-3e62-491a-b5fa-39a0d3518164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dockeydown</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb637e32-890d-45f9-bca5-243c17057493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dockeyup</name>
      <type>Main</type>
      <value>sendmessage</value>
      <webElementGuid>fb5e8f57-6fac-4915-8549-f15ed435d7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>txtarea-id</name>
      <type>Main</type>
      <value>6de4586e9da63ef9ac3d2731d6aea8bd4fe2948f17b6646f2c514edb280b4a5ca6c5a663249eaea9</value>
      <webElementGuid>fc280a47-a0e9-45e1-b0a1-9116c4c98b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e1784c75-01bb-49eb-8388-c37dbb96feb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msgarea&quot;)</value>
      <webElementGuid>065083ee-1fef-4062-968b-2eaaeaa0b812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>9010bcb0-1a99-4e6c-90b0-82ad86a3be33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='msgarea']</value>
      <webElementGuid>388ff0b4-7e66-40da-af28-cca924fb7523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='msgbox_main']/div/textarea</value>
      <webElementGuid>bc4181fd-485f-42e2-8727-3b139e729713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>27055084-a2ad-4bf5-846e-2c5dcef32c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Type your message and hit Enter' and @id = 'msgarea']</value>
      <webElementGuid>97644683-e73f-47bf-90f3-076a08265874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
