<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Please enter a valid email address_bc02c9</name>
   <tag></tag>
   <elementGuidId>1f908794-63a1-4052-8d4a-12ece148848a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='msgarea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#msgarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ffd885b-d1b2-4e5d-a882-c6570dab66f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your message and hit Enter</value>
      <webElementGuid>33c77905-825c-4493-9fdc-223e80db60db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msgarea siq-message-textarea</value>
      <webElementGuid>1429f2ed-49b5-4976-bb9a-635a27462853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>purpose</name>
      <type>Main</type>
      <value>question</value>
      <webElementGuid>73e8bdc3-e3de-497c-a78f-41d89d782031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>info</name>
      <type>Main</type>
      <value>question</value>
      <webElementGuid>4c03ce7b-c248-400c-8598-5451e233d8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5af6ca51-5467-4a29-8653-599c1e69907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>msgarea</value>
      <webElementGuid>a97a0ea3-aabc-4f72-8bfe-94077e30e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dockeydown</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>08a5a7ae-31f0-4446-8c5a-c302afe79e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dockeyup</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>24aef016-61d9-4046-bdd2-38ea7caeeb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>required charlimit 2048</value>
      <webElementGuid>d6e5486c-3b7b-4a10-a0cf-be2f0e0bad2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msgarea&quot;)</value>
      <webElementGuid>020b45d5-6dc1-4131-8a44-de54bc858123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_The 1st Player vs Player Crypto Action_dba80c/iframe_concat(id(, , siqiframe, , ))_siqiframe</value>
      <webElementGuid>863cd768-e5dd-4f29-b1ba-d5afc51973c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='msgarea']</value>
      <webElementGuid>a570a594-e042-40bc-98c0-ddf430f7c84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='window-ribbon']/section/div[4]/div/textarea</value>
      <webElementGuid>13c98d02-cf97-4c54-85f5-add1b9ba7a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4a961796-7994-41dc-81e0-5e023132de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Type your message and hit Enter' and @type = 'text' and @id = 'msgarea']</value>
      <webElementGuid>308c9121-3ed3-433c-8822-8a4b7c7e1bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
