<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_maxquestofficialMessageFollow1 post73 f_f1bb63</name>
   <tag></tag>
   <elementGuidId>1c0fbb43-dfe0-44fd-8ced-0830c897f125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_Qv']/div/div/div/div/div/div/div/div/section/main/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._aa_y._aa_z</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00fc0677-edd5-4f9d-8b58-f5decc566521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aa_y _aa_z</value>
      <webElementGuid>d21e3cba-56c0-4d71-8e91-8de109171c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>maxquestofficialMessageFollow1 post73 followers1 followingMaxQuestVideo game#1 Crypto Player vs Player Action Game! No purchase necessary — play for fun or to WIN real crypto prizes.PLAY NOW➡️maxquest.com maxquest.comPostsReelsTagged</value>
      <webElementGuid>871e9229-4f0a-41ce-898d-f0c091ce670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_Qv&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x1ja2u2z x1n2onr6 xdt5ytf x78zum5&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x10cihs4 x1t2pt76 x1n2onr6 x1ja2u2z&quot;]/section[@class=&quot;_a997 _a998&quot;]/main[@class=&quot;_a993 _a995&quot;]/div[@class=&quot;_aa_y _aa_z&quot;]</value>
      <webElementGuid>6ec40573-8d0b-4ef4-81bd-637716553d2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_Qv']/div/div/div/div/div/div/div/div/section/main/div</value>
      <webElementGuid>65ed3159-cf75-46cf-a3b0-571bd2138f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>1f04dd71-1692-4f48-8ffd-e3231027ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'maxquestofficialMessageFollow1 post73 followers1 followingMaxQuestVideo game#1 Crypto Player vs Player Action Game! No purchase necessary — play for fun or to WIN real crypto prizes.PLAY NOW➡️maxquest.com maxquest.comPostsReelsTagged' or . = 'maxquestofficialMessageFollow1 post73 followers1 followingMaxQuestVideo game#1 Crypto Player vs Player Action Game! No purchase necessary — play for fun or to WIN real crypto prizes.PLAY NOW➡️maxquest.com maxquest.comPostsReelsTagged')]</value>
      <webElementGuid>a43cc384-1b8b-4a08-b7e3-ce3e11deed9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
