<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Max Rewards</name>
   <tag></tag>
   <elementGuidId>96d46179-4b59-4634-8413-56f3ab558540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-105']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-105 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a351fcf-e2af-4d5e-bdad-ed9c597d8468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/max-rewards/</value>
      <webElementGuid>b33a1c18-b8bc-464f-8e8c-e186ede6a556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Max Rewards</value>
      <webElementGuid>70e9978f-716e-45ab-96ee-b272854958e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-105&quot;)/a[1]</value>
      <webElementGuid>e5a45a88-edee-4526-9008-a9cf671d2eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>010436d5-bebe-402c-83e3-7752e44dbe35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/max-rewards/</value>
      <webElementGuid>a52506c8-8127-4008-a464-17460fde04d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Max Rewards</value>
      <webElementGuid>bd9d2925-5c5e-41be-ba18-e3720926c158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-105&quot;)/a[1]</value>
      <webElementGuid>0af2c35a-43d3-49c8-8b88-f62837f2df9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-105']/a</value>
      <webElementGuid>2962245e-1313-4861-9068-f50f694917d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Max Rewards')]</value>
      <webElementGuid>7860dc31-8a47-47ba-a536-1d54ca20a3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triple Max Blast'])[1]/following::a[1]</value>
      <webElementGuid>3173f7a1-f2c7-4036-a03a-ad4c3b8b4c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fastfire'])[1]/following::a[2]</value>
      <webElementGuid>e406d7ab-078b-4391-9bd5-bbc3863474f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Friends'])[1]/preceding::a[1]</value>
      <webElementGuid>a020edb0-d0d7-465e-be2f-3d0c4925accd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casino'])[1]/preceding::a[2]</value>
      <webElementGuid>c03feb5c-1e5d-4077-93f7-e4fce5dbbfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Max Rewards']/parent::*</value>
      <webElementGuid>bbaab6e3-3405-4dd4-8953-f7a4706fa020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/max-rewards/')]</value>
      <webElementGuid>7f45a7c6-1093-44e7-99b7-6f7e05b09d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>cacc69c1-2a9e-4d68-bd21-07e384d8176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/max-rewards/' and (text() = 'Max Rewards' or . = 'Max Rewards')]</value>
      <webElementGuid>127e6c60-ef34-486f-b01c-52493d42f9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>e4078fbe-3553-4daf-80d7-27d412a20970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
