<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Casino</name>
   <tag></tag>
   <elementGuidId>22c65e22-e04e-43f8-ad27-73c57d105708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-4159']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-4159 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03f2ca70-10e1-469f-bf9c-20a7a1a84c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/casino/</value>
      <webElementGuid>40d29cde-4527-42fd-9da9-a8d60b6cde2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casino</value>
      <webElementGuid>a13ede38-cbd2-4b97-8d6b-0d15519e6b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-4159&quot;)/a[1]</value>
      <webElementGuid>1dd25ae7-9840-467c-8bfe-30d6428ea0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-4159']/a</value>
      <webElementGuid>5c16cbb3-84cb-43db-bfd7-30140254d92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Casino')]</value>
      <webElementGuid>749cdc13-9a13-4241-8797-31d422e2a37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Friends'])[1]/following::a[1]</value>
      <webElementGuid>d144f491-eb81-4408-bae6-f262fd265906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max Rewards'])[1]/following::a[2]</value>
      <webElementGuid>dc1983fb-8f07-4d8c-ad42-0cd931bacf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome back!'])[1]/preceding::a[1]</value>
      <webElementGuid>42c56d22-bb95-495c-bd8e-2a1c1d0c0748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The username or password was incorrect. Please try again.'])[1]/preceding::a[1]</value>
      <webElementGuid>eb53853f-bc18-426b-a900-f49c1d2fa2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Casino']/parent::*</value>
      <webElementGuid>136bcf64-f893-47d0-b35d-65ee765f7518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/casino/')]</value>
      <webElementGuid>98087cf7-1201-475f-a163-d85f08209b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>c09e31df-31f5-4395-9280-0d53bde75e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/casino/' and (text() = 'Casino' or . = 'Casino')]</value>
      <webElementGuid>84d986ef-062a-447b-8165-1f90f0a02bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
