<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_REFER FRIENDS</name>
   <tag></tag>
   <elementGuidId>740bc9c0-e0ad-455a-b7b5-2afe5290c1d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-c8fe13c6']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-c8fe13c6 > h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5e3f462f-d58e-4dfb-adbd-ef81e15be953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REFER FRIENDS</value>
      <webElementGuid>4da32c27-24de-4d67-901d-76720b604741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-c8fe13c6&quot;)/h1[1]</value>
      <webElementGuid>c072133c-8cc6-4a28-a235-a36c18242513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>19b90b09-f440-46d2-822b-c641f7c6cff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REFER FRIENDS</value>
      <webElementGuid>f0d395b5-8cff-4630-973b-faf5fe92cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-c8fe13c6&quot;)/h1[1]</value>
      <webElementGuid>603227eb-b360-4b54-b81a-05bd88fa5350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-c8fe13c6']/h1</value>
      <webElementGuid>f3ac778f-8891-4b0c-8efa-4eb167de4311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Friends'])[2]/following::h1[1]</value>
      <webElementGuid>6ede0760-25db-4415-9024-0dfba0250dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/following::h1[2]</value>
      <webElementGuid>b4f5f52a-b450-4ae3-8dee-cf13cda68c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h1</value>
      <webElementGuid>e5e65941-0e3a-4819-9e7c-5f713b0bc128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'REFER FRIENDS' or . = 'REFER FRIENDS')]</value>
      <webElementGuid>c67be284-7540-44cc-ac64-f30bb16b7483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
