<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grab all your friends and start earni_cf3092</name>
   <tag></tag>
   <elementGuidId>5eb52e02-8957-485b-99aa-52a0716c05cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d2e6d54-754b-430d-ba8d-5313136363fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>e3a24b94-bc91-4450-8f95-752fe79ce762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a56c3c69-e2f2-4ea4-9937-955fc226da33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email6</value>
      <webElementGuid>8b1dd8f6-b1ab-440d-96c0-b89cc6596906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email6</value>
      <webElementGuid>e83b8ac8-d99d-497f-bebe-26a4e9f3ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email 6</value>
      <webElementGuid>fd9346ad-b22a-41f5-903a-fd54fe58c133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email6&quot;)</value>
      <webElementGuid>e0688a77-a591-49a7-aeca-39e50724dd1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email6']</value>
      <webElementGuid>bc9767e8-a50b-4dcd-ae8c-6d61a3ff10ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='raf-form-rows']/div[3]/div[2]/div/input</value>
      <webElementGuid>b4a0b474-5a86-4880-9f74-bda0f116da38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>786eb09e-5caa-4e9d-b425-3903b7bc1e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email6' and @id = 'email6' and @placeholder = 'Enter email 6']</value>
      <webElementGuid>0c33e324-d576-46ed-8767-72cb18448479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
