<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grab all your friends and start earni_0079a4</name>
   <tag></tag>
   <elementGuidId>b974c5f5-03c0-405e-a00b-ef48e05379c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>402a1a8d-8e8c-48b2-aa29-8e2c49cd270f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>16c84482-200e-4f88-848a-cd788aef1ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ba759f9e-2923-4e17-9727-637384ba4b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email5</value>
      <webElementGuid>25c45664-6b7b-4c22-ac29-3d925d6ce6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email5</value>
      <webElementGuid>3e671c01-0089-4c7c-a332-76459d4d94c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email 5</value>
      <webElementGuid>a2d8fa13-6081-4956-a02c-d497f2a872bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email5&quot;)</value>
      <webElementGuid>08c93d89-bb96-48af-bcb9-c89f861f966a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email5']</value>
      <webElementGuid>77f401f8-52d9-4952-a58b-cdf0c4b858ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='raf-form-rows']/div[3]/div/div/input</value>
      <webElementGuid>19042b10-02b1-48de-8187-256022a21b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>e0ef8406-f7b8-42d1-a1ec-59ec92225494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email5' and @id = 'email5' and @placeholder = 'Enter email 5']</value>
      <webElementGuid>59fae80f-71ae-4520-b546-14c5e9b40d9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
