<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grab all your friends and start earni_4ddf63</name>
   <tag></tag>
   <elementGuidId>eaa2d496-21a1-4c44-b42e-5603e5ff605f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc53f9f0-f54d-4680-991f-bf9592956bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>7f7998a3-b3e3-4a9b-8ce0-f139924c3855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>61008920-6d14-4e4b-ad12-1c869d3de605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email3</value>
      <webElementGuid>9fec2052-9c04-4a7a-a16e-d53a30bc93bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email3</value>
      <webElementGuid>e45bc3a1-6b76-4761-b07b-50589761c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email 3</value>
      <webElementGuid>f14bd2a1-f5c8-41e4-8f61-c6b72f70f2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email3&quot;)</value>
      <webElementGuid>5dcb1780-ecf7-4388-a67f-01b6d1131329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a80bfec7-25b9-475d-8360-70a8cbb89f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-field</value>
      <webElementGuid>1f418d3b-ba1a-4ab2-bad6-7e9512361778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>aac5a6d6-c34d-4a02-a769-f993b22f996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email3</value>
      <webElementGuid>16370a6e-0a0f-4b64-88d3-022a3c7e4a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email3</value>
      <webElementGuid>608fcdc1-4a6c-439c-a547-db5f0015d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email 3</value>
      <webElementGuid>eb3f241e-692f-499a-9516-230f5234199a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email3&quot;)</value>
      <webElementGuid>3c4e9615-5fb9-4aa0-8a7e-3f8e13b3a9c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email3']</value>
      <webElementGuid>ef902cad-4c61-44ad-9a6d-201df920c88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='raf-form-rows']/div[2]/div/div/input</value>
      <webElementGuid>9e64e995-b21b-4c1f-a64f-d86ec4dd428c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
      <webElementGuid>48d75732-649a-4b05-874b-a569957c6d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email3' and @id = 'email3' and @placeholder = 'Enter email 3']</value>
      <webElementGuid>267740e3-95ca-4c70-bbc0-f2971fb6c53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
