<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Please make a purchase to enable Friend invites</name>
   <tag></tag>
   <elementGuidId>36614112-6e1b-44a3-ba2a-5754d2fde31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='global-modal-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-modal-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b0453ea5-e2f2-44fb-9a31-d35b62dfde83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-text</value>
      <webElementGuid>d721dc35-3102-48b5-b463-a385db12cb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>global-modal-message</value>
      <webElementGuid>9ad70156-ca9c-431e-b15f-36003b1941a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please make a purchase to enable Friend invites</value>
      <webElementGuid>063f1fe0-1b63-449f-b692-3e1bf1486fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-modal-message&quot;)</value>
      <webElementGuid>0a735505-e7b8-4660-9b9a-272174999636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='global-modal-message']</value>
      <webElementGuid>96a42d7c-bf36-46d0-a68b-664d1fbadfa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-modal']/div/div/div[2]/p</value>
      <webElementGuid>f75820f2-739e-4fce-b8e2-afa347bde647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer friends'])[1]/following::p[1]</value>
      <webElementGuid>38c62590-3d46-4dca-a302-fd751148b9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copied!'])[1]/following::p[1]</value>
      <webElementGuid>eee1a224-4f73-4a83-9446-df7c2c576509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::p[2]</value>
      <webElementGuid>c3ca351e-d6de-48cc-941b-10e6b7aaf41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::p[2]</value>
      <webElementGuid>181e9c25-e10c-4d6a-8bd7-7e5935b8ae5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please make a purchase to enable Friend invites']/parent::*</value>
      <webElementGuid>b24ee328-6c26-4a95-ae0e-301c0701ee5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/div[2]/p</value>
      <webElementGuid>702dfb6e-d3a9-4f58-91a3-5499f0f5af3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'global-modal-message' and (text() = 'Please make a purchase to enable Friend invites' or . = 'Please make a purchase to enable Friend invites')]</value>
      <webElementGuid>47e5522d-31b7-4f78-997c-dace4fa90779</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
