<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_x</name>
   <tag></tag>
   <elementGuidId>6873e1fe-3055-42bb-a433-c822b0f1ab76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-modal']/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#global-modal > div.modal-dialog.modal-sm > div.modal-content > div.modal-header > button.close > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12c7da32-0505-4112-af0e-f0a933c5aa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3038ad19-3c90-4820-ba96-b9ccfbcd8906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>c8ccc984-cb70-4be1-a35a-73b3779b663b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-modal&quot;)/div[@class=&quot;modal-dialog modal-sm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/button[@class=&quot;close&quot;]/span[1]</value>
      <webElementGuid>c9748265-189e-480f-8c38-cbf54fa9115b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-modal']/div/div/div/button/span</value>
      <webElementGuid>cfbd78e0-5ef8-492b-bfbe-e0ac6cbe536c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copied!'])[1]/following::span[1]</value>
      <webElementGuid>bddd631b-5a4a-4e8c-8370-c478cc85e009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COPY BONUS CODE'])[1]/following::span[2]</value>
      <webElementGuid>5a624c65-e119-4d68-ba73-4a2b93c3c5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer friends'])[1]/preceding::span[1]</value>
      <webElementGuid>dbc187a6-807b-4871-8458-82da32169d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::span[2]</value>
      <webElementGuid>2faf70e4-2e91-43d8-8a06-fe74aeafe267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/div/button/span</value>
      <webElementGuid>8a400e95-412a-4f7d-93b8-45f17857e018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'x' or . = 'x')]</value>
      <webElementGuid>42fdf649-b8ae-409d-8167-4de0baddc180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
