<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crypto</name>
   <tag></tag>
   <elementGuidId>eca18b61-ca15-428c-9a52-c777ad881f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1739']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1739 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e87fc2a0-1477-4499-90ee-338c909952cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/crypto/</value>
      <webElementGuid>8386fe07-79b2-49a2-980f-cc1823aff0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Crypto</value>
      <webElementGuid>d5387a2f-92ed-45a7-8635-c2965ab9d1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1739&quot;)/a[1]</value>
      <webElementGuid>098b7d35-9ff1-4852-9a0a-300fbb1d26ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1739']/a</value>
      <webElementGuid>e17a99b3-9047-45fa-909a-d10e95f4aeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Crypto')]</value>
      <webElementGuid>f5af74f8-2e01-4c53-b3f4-3f9c73128dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::a[1]</value>
      <webElementGuid>c73454eb-0e87-4eef-b0ce-f31d64522ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Policy'])[1]/following::a[2]</value>
      <webElementGuid>4d14673f-66ff-4b4b-9cf1-c9851c6ed248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We', &quot;'&quot;, 're Online!')])[1]/preceding::a[7]</value>
      <webElementGuid>652bc572-50df-4f15-9e8a-2273236c358d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'menu-item-1739', '&quot;', ')/a[1]')])[1]/preceding::a[7]</value>
      <webElementGuid>e29b5353-cb97-4d1e-856b-a7c1d7712ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crypto']/parent::*</value>
      <webElementGuid>3449ce80-8be6-4f7c-9096-a7f953c0bc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/crypto/')]</value>
      <webElementGuid>57a5ec95-a0cc-4b8a-9e6d-663d9434027d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[6]/a</value>
      <webElementGuid>d41a828c-dea2-47a6-bd6f-c4dffd1afc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/crypto/' and (text() = 'Crypto' or . = 'Crypto')]</value>
      <webElementGuid>e8703e95-dff5-410a-b828-61b6640ab6aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
