<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Help Center</name>
   <tag></tag>
   <elementGuidId>432c1177-ab6d-440e-9b9a-e9cfb085d89f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-128']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-128 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a41e0088-786e-499b-af2b-81bdc00acf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/help-center/</value>
      <webElementGuid>fbec72db-d3ba-4e00-add3-d921fdee986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help Center</value>
      <webElementGuid>317701a2-e527-40bc-8ff7-d32819c663d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-128&quot;)/a[1]</value>
      <webElementGuid>da0bf550-9fa4-4809-868d-41b4e7527969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-128']/a</value>
      <webElementGuid>d4186904-2dd3-4489-8b87-bd79a08f8ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Help Center')]</value>
      <webElementGuid>e538d1ca-972c-4756-9c42-85bcbebe2a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@maxquest.com'])[1]/following::a[1]</value>
      <webElementGuid>675b361b-a23c-4cea-996f-a4bfd6133a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to perform customer due diligence including ID verification.'])[1]/following::a[2]</value>
      <webElementGuid>483c5a98-c4cb-4deb-9a36-edc8fc425fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::a[1]</value>
      <webElementGuid>951e87f8-a7a8-4a2e-beff-7a2f26c26aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[2]/preceding::a[2]</value>
      <webElementGuid>3c120187-67c1-4670-a8d4-101989bc9bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help Center']/parent::*</value>
      <webElementGuid>4534f3bc-36b8-4138-8a53-816cb6964733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/help-center/')]</value>
      <webElementGuid>c1d231f3-e5f3-4b8b-b1ba-eca35cd12b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>812f383e-6f6a-4906-9ac9-08161af9a28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/help-center/' and (text() = 'Help Center' or . = 'Help Center')]</value>
      <webElementGuid>9e3f5acd-8e4b-40bf-b629-510f8723fac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
