<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy Policy</name>
   <tag></tag>
   <elementGuidId>56cbd5f9-c97d-4b1a-bace-67c16adce785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-132']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-132 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08567543-71e5-4298-ae6c-04d608b00281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/privacy-policy/</value>
      <webElementGuid>99833211-a45b-4305-b141-95c111cdd59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>ffeda38f-b8f2-431e-8aa9-c0ba4e8e3bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy Policy</value>
      <webElementGuid>14f7d311-6b68-4a06-b098-8d3be84e9ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-132&quot;)/a[1]</value>
      <webElementGuid>ce89da3f-e4a9-45f6-9d82-90dc763f86bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-132']/a</value>
      <webElementGuid>de430c75-fc52-4116-99b4-6c99dde46ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Privacy Policy')])[3]</value>
      <webElementGuid>d4586b95-6e8b-499d-8c7b-6f698fcb75e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Policy'])[1]/following::a[1]</value>
      <webElementGuid>62d4acda-ef4d-4225-9723-11d2c393782e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[2]/following::a[2]</value>
      <webElementGuid>4b46ffbc-a12a-4a51-b3a5-4085ffae3adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crypto'])[1]/preceding::a[1]</value>
      <webElementGuid>43258b95-3f86-4ee4-b005-c1769a35fad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'menu-item-132', '&quot;', ')/a[1]')])[1]/preceding::a[8]</value>
      <webElementGuid>95d4a5b2-9d55-409d-8ed0-44194b028d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/privacy-policy/')])[4]</value>
      <webElementGuid>cec8815a-bf0f-4040-83b5-5524e35ff5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>83ba0809-7f29-47cc-a4d9-64e91373bc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/privacy-policy/' and (text() = 'Privacy Policy' or . = 'Privacy Policy')]</value>
      <webElementGuid>2e974dd7-e966-4113-94f5-8d64260d6fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
