<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PLAY NOW</name>
   <tag></tag>
   <elementGuidId>a57d534e-b962-4e39-8fdc-273b5a3733f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-d5cf57fb']/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.casino-game-pay-demo.world-play-now-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f46a627-0b33-4f88-8f53-240b96c47018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button casino-game-pay-demo world-play-now-btn</value>
      <webElementGuid>cc257d35-980c-4051-a37f-1e200ab1aa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#homePlayCasinoGame</value>
      <webElementGuid>f8acf382-f003-41bf-b63a-aa11a80a1019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-demolink</name>
      <type>Main</type>
      <value>/game?gameId=838</value>
      <webElementGuid>b4520f71-b0a9-418d-8b7d-ce5afdd65b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY NOW</value>
      <webElementGuid>5005dd5f-a366-4e9e-9c3d-de203f87c365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-d5cf57fb&quot;)/p[@class=&quot;button-center-mobile&quot;]/a[@class=&quot;button casino-game-pay-demo world-play-now-btn&quot;]</value>
      <webElementGuid>ef554a95-4ac9-4496-9876-1ed9d2fe2bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-d5cf57fb']/p/a</value>
      <webElementGuid>70c8c106-6211-45a4-9b2f-8c118b06db14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PLAY NOW')]</value>
      <webElementGuid>7b9936a5-800d-42af-9f34-5ba66db4a88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See More'])[1]/following::a[1]</value>
      <webElementGuid>35dc572a-c9ef-4941-91bc-56034368993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[2]</value>
      <webElementGuid>5f1a6f53-d480-4b56-bc71-7c66e6d7a92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLAY NOW'])[2]/preceding::a[1]</value>
      <webElementGuid>745fdd88-24ad-4e12-a798-fae4f3b58177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See More'])[2]/preceding::a[2]</value>
      <webElementGuid>868e14a9-0068-4a0a-aedc-dc47794f6468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PLAY NOW']/parent::*</value>
      <webElementGuid>d37625e4-99cc-4f5e-8ab3-889d9ca65b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#homePlayCasinoGame')]</value>
      <webElementGuid>db634b55-278f-441a-9ddf-4d31716f8086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/a</value>
      <webElementGuid>32cc638a-3936-4df4-b9a2-c45ec4243705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#homePlayCasinoGame' and (text() = 'PLAY NOW' or . = 'PLAY NOW')]</value>
      <webElementGuid>232a28cd-9f2e-482d-97f1-952d2a3b8539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
