<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Triple Max Blast</name>
   <tag></tag>
   <elementGuidId>11337078-d59b-4002-ad6a-af13a7aea979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3232']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3232 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6c73776-9883-48ea-b408-cabbed14920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/triple-max-blast/</value>
      <webElementGuid>12026414-4145-4705-ab05-c1154c23de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Triple Max Blast</value>
      <webElementGuid>f61e3170-495b-4af5-9555-051ffe2bb317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3232&quot;)/a[1]</value>
      <webElementGuid>ad2dc8ed-e676-4955-b510-d3fd97b88c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8eddcece-a21b-4621-a636-46e66199c366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/triple-max-blast/</value>
      <webElementGuid>2c193737-0c4d-4d48-a35e-c8a9ac2aa15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Triple Max Blast</value>
      <webElementGuid>bf3a08fd-f597-4629-b66b-64c6a4103961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3232&quot;)/a[1]</value>
      <webElementGuid>0f694c0d-cf2e-4955-a996-28248833efe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3232']/a</value>
      <webElementGuid>061465be-7360-4a4e-ab78-f1bbe71defe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Triple Max Blast')]</value>
      <webElementGuid>6000a2c5-6dc8-466a-b01f-53457e4ece5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fastfire'])[1]/following::a[1]</value>
      <webElementGuid>8c916c85-951c-4134-aa61-bb80f5075986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Battleground'])[1]/following::a[2]</value>
      <webElementGuid>3fbb5657-84a5-493b-aa11-063eaee41f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max Rewards'])[1]/preceding::a[1]</value>
      <webElementGuid>267d90bd-af80-4a20-b858-edfa123b0f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Friends'])[1]/preceding::a[2]</value>
      <webElementGuid>d6bfd43e-f3cd-4780-90ec-3d4c1462d06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Triple Max Blast']/parent::*</value>
      <webElementGuid>d14caee9-1d01-432b-86c9-ba651fc684e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/triple-max-blast/')]</value>
      <webElementGuid>2a77bb1c-adf9-45d5-9ab5-ef96ef9bddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>f6a32cfd-594b-4342-b320-ca84aeede9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/triple-max-blast/' and (text() = 'Triple Max Blast' or . = 'Triple Max Blast')]</value>
      <webElementGuid>ca91d50e-2d3e-4011-9625-3561c0e5cbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>b41ad017-c311-4f1a-b6df-344cad8d41c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
