<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Game Max Quest. Version 1.0.6. Date 27.09.2022. FPS 144_app-screen</name>
   <tag></tag>
   <elementGuidId>959495ec-d1ee-4059-b0dc-eb7d991a1f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.app-layout-layer.app-layer-preloader > canvas.app-screen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>37c0b255-0279-4eb6-8986-3b4ad7bf8644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-screen</value>
      <webElementGuid>a4404ce3-2ac9-4fba-99d8-4bf6b0e3ed72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>e7d93d04-79fb-42be-bd01-71f76d22521e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1130</value>
      <webElementGuid>e6760164-c173-41b1-8e5b-1c49a974296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app-layout&quot;]/div[@class=&quot;app-layout-layer app-layer-preloader&quot;]/canvas[@class=&quot;app-screen&quot;]</value>
      <webElementGuid>65dff608-345b-48c8-9544-942111cf68f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Fastfire  MaxQuest/iframe_The game has been stopped_gameFrame</value>
      <webElementGuid>d831985f-f675-4485-b95f-03c2733680ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/canvas</value>
      <webElementGuid>3d648df4-0810-4819-8922-dbd562e9d05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
