<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Casino_menu-overlay</name>
   <tag></tag>
   <elementGuidId>cbbbd2f2-fe13-44e1-a614-f2930f356107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-overlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bea38c75-2154-4623-87ef-e658ecf8a8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-overlay</value>
      <webElementGuid>070c8323-283c-4967-b6ca-de4e86953869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-overlay&quot;)</value>
      <webElementGuid>d5f3f14c-d3dd-413a-a41d-322d8f4d736a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='menu-overlay']</value>
      <webElementGuid>e1e27238-dd09-47a9-8a9b-c90796fcdeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/div[2]/div/div/div[3]</value>
      <webElementGuid>af18d7e7-d644-463c-be48-7b626916e9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>d6587356-d496-43bb-83d2-a3dd2f6c5983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menu-overlay']</value>
      <webElementGuid>6a89c5eb-1783-44ff-aea3-b92d9614326c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
