<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fastfire_vce-single-image-inner vce-sin_5f2b87</name>
   <tag></tag>
   <elementGuidId>53a9e98f-b4a7-4d8a-a3b7-591ae767a74d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-52f387fc']/figure/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vce-single-image-inner.vce-single-image--absolute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d7aa2d7-b4e3-40fb-b989-554bbfa693bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-single-image-inner vce-single-image--absolute</value>
      <webElementGuid>aca28345-49d3-4388-b4f0-814927d424ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-52f387fc&quot;)/figure[1]/div[@class=&quot;vce-single-image-figure-inner&quot;]/div[@class=&quot;vce-single-image-inner vce-single-image--absolute&quot;]</value>
      <webElementGuid>b132b420-486f-4f46-afa8-48ed5df1ccd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c73a3d60-2c1c-4041-af5d-a1eb02b3c180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-single-image-inner vce-single-image--absolute</value>
      <webElementGuid>2df4acc4-8155-41f0-98db-856f36898331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-52f387fc&quot;)/figure[1]/div[@class=&quot;vce-single-image-figure-inner&quot;]/div[@class=&quot;vce-single-image-inner vce-single-image--absolute&quot;]</value>
      <webElementGuid>fad0c024-6c58-4fbf-a58f-e89845f58e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75aa3055-5368-4007-9552-0aafcee44a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-single-image-inner vce-single-image--absolute</value>
      <webElementGuid>f5667177-e304-4189-8b11-8ce437867378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-52f387fc&quot;)/figure[1]/div[@class=&quot;vce-single-image-figure-inner&quot;]/div[@class=&quot;vce-single-image-inner vce-single-image--absolute&quot;]</value>
      <webElementGuid>61dd5a1e-4704-4b55-b17f-56d3ea6e7d10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-52f387fc']/figure/div/div</value>
      <webElementGuid>77449fc8-c595-4a21-ac20-8d415f5b6c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fastfire'])[2]/following::div[28]</value>
      <webElementGuid>458dd84b-fa28-4550-8c3b-3866294b4578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/following::div[33]</value>
      <webElementGuid>2914db6d-baae-4f55-ba62-717c9f2a5a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have what it takes?'])[1]/preceding::div[1]</value>
      <webElementGuid>a6b55e5c-6f2f-43be-b85b-d49e7f5389c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::div[3]</value>
      <webElementGuid>b16abc46-b9ef-4737-8f00-c534eb60c0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/div</value>
      <webElementGuid>d2db6acf-cec0-4922-81e5-4e09c837364e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
