<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_The game has been stopped_gameFrame (1)</name>
   <tag></tag>
   <elementGuidId>4bac56c6-26de-4b6a-9c3c-28132a29368c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gameFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gameFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b9ab613-8d7f-4246-9f4d-6639a95bcbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gameFrame</value>
      <webElementGuid>579d516d-834f-4205-a6c3-929a3560ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mqtech-mqb.maxquest.com/cwstartgamev2.do?bankId=6275&amp;gameId=859&amp;lang=en&amp;token=OAMC292IYCPJOJJF10FW7CPESJFRKEWB&amp;mode=real</value>
      <webElementGuid>37ed257d-fde1-4197-833b-5559bf0c454a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a44882e6-1865-4bb6-b7ce-8b07f449d29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>15e696f6-a714-40e8-8531-dfa505437c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b6202b8-e888-408f-a02c-7304f927b7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8ac2aa0d-00af-4db6-9c09-f578f9c98611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameFrame&quot;)</value>
      <webElementGuid>3760f55e-26a0-420f-9dd1-910d61fa5031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Fastfire  MaxQuest/iframe__gameUrlFrame_1</value>
      <webElementGuid>ccaae9f3-ba49-483d-966a-dedcda7a3647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gameFrame']</value>
      <webElementGuid>4e73fa0a-a27a-4e91-bebd-7e24188aa821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5f2a3b22-e61f-4576-9f2a-fe53aec5f642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gameFrame' and @src = 'https://mqtech-mqb.maxquest.com/cwstartgamev2.do?bankId=6275&amp;gameId=859&amp;lang=en&amp;token=OAMC292IYCPJOJJF10FW7CPESJFRKEWB&amp;mode=real']</value>
      <webElementGuid>69366977-e5e7-44d8-8177-d19295559c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
