<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__gameUrlFrame_1</name>
   <tag></tag>
   <elementGuidId>e8563743-7d38-4a97-9d99-86b72c3e3234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='gameUrlFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;gameUrlFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f062d601-5fb8-44e5-a6da-0de20b913b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item</value>
      <webElementGuid>854c0480-5629-4649-8518-39017097f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gameUrlFrame</value>
      <webElementGuid>9f49d8d2-c838-441f-88d0-27a0af8837ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/game?gameId=859</value>
      <webElementGuid>5bcd1f04-5ba6-4765-b07e-8819e92eb9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePlayCasinoGame&quot;)/div[@class=&quot;modal-dialog modal-xl&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9&quot;]/iframe[@class=&quot;embed-responsive-item&quot;]</value>
      <webElementGuid>563adcd2-3e87-4b31-908a-0a88ca61b1d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='gameUrlFrame']</value>
      <webElementGuid>a95fd8c0-f123-488d-bbe4-4c4dfdd60b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homePlayCasinoGame']/div/div/div/iframe</value>
      <webElementGuid>221be30d-93a3-4e58-be31-696b5e4fabd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9613dad8-9e19-46cc-9fc4-fb74eca9a80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'gameUrlFrame' and @src = '/game?gameId=859']</value>
      <webElementGuid>9f570e6c-713e-4629-878c-1a0ad3c1787b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
