<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_The game has been stopped_gameFrame</name>
   <tag></tag>
   <elementGuidId>20301bac-ad30-464f-9b63-ca7b80b3d496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gameFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gameFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6b5c7470-9b62-4a8e-a081-582a651f4da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gameFrame</value>
      <webElementGuid>13fa7170-6e47-48b2-9d4b-66b590e53a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mqtech-mqb.maxquest.com/cwstartgamev2.do?bankId=6275&amp;gameId=838&amp;lang=en&amp;token=OAMC292IYCPJOJJF10FW7CPESJFRKEWB&amp;mode=real</value>
      <webElementGuid>5e4518e9-cc09-4c75-9a13-9ee78abdd6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4f4b4028-408a-4dcf-ac91-8601ee230855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d0c11b1f-ba0e-4baf-98ce-fc894dc79ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0afde061-380e-4356-af35-506ab15a35f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fbbd1d75-5584-4391-833c-1dc33dd20d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gameFrame&quot;)</value>
      <webElementGuid>23c01036-7586-4473-871d-316ec44eae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Fastfire  MaxQuest/iframe__gameUrlFrame</value>
      <webElementGuid>69bd5282-1a6e-4fbc-99cb-6e07964713ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gameFrame']</value>
      <webElementGuid>150dd51d-e7d1-494b-a1ea-d63c71fda148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d2788080-7b6c-46f0-a1b2-40b1c8f02316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'gameFrame' and @src = 'https://mqtech-mqb.maxquest.com/cwstartgamev2.do?bankId=6275&amp;gameId=838&amp;lang=en&amp;token=OAMC292IYCPJOJJF10FW7CPESJFRKEWB&amp;mode=real']</value>
      <webElementGuid>58182e3e-5def-49c6-8038-9f26f874b801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
