<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_General</name>
   <tag></tag>
   <elementGuidId>971f4afa-3009-421c-9681-6ca66df062e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-269d5bab']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a647589d-8d44-49da-993d-917b19e6de9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>ed8b2709-4ea0-4487-ad7f-5266225e1093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                     General 
                    </value>
      <webElementGuid>865e07a3-1362-4b28-ad7e-a0a49c48e302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-269d5bab&quot;)/div[@class=&quot;faqs-listing&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;faq-category-box&quot;]/div[@class=&quot;heading&quot;]</value>
      <webElementGuid>38ff829a-e455-4492-a9a2-c921449f9a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-269d5bab']/div/div/div/div/div</value>
      <webElementGuid>017cc406-2cde-43a4-9d69-f3d30867dd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/following::div[14]</value>
      <webElementGuid>dbab4dc3-60bf-42ec-a1da-536cbf826c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is MaxQuest?'])[1]/preceding::div[1]</value>
      <webElementGuid>d23d6f76-5776-4ae5-8b6d-148a5065f88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>f8f8c471-638f-4095-9885-30473dcfdd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                     General 
                    ' or . = ' 
                     General 
                    ')]</value>
      <webElementGuid>0d307719-5808-4f3a-bb96-c441afe21365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
