<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fastfire</name>
   <tag></tag>
   <elementGuidId>da18a9a6-bcf9-4607-9d91-49c16bf87715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-269d5bab']/div/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d9d3b79-ac2a-403c-9b01-d7993c24f74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>50717b17-13da-4ba3-98fc-9f7f341660ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                     Fastfire 
                    </value>
      <webElementGuid>ecc2cfcb-3785-42e4-af33-1a6e9e788f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-269d5bab&quot;)/div[@class=&quot;faqs-listing&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;faq-category-box&quot;]/div[@class=&quot;heading&quot;]</value>
      <webElementGuid>65ff7a62-ae59-4474-974f-562cba9bd5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-269d5bab']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>9ece6222-1e0d-4b39-8e07-848ced85df84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I play Mission: Amazon Battleground?'])[1]/following::div[5]</value>
      <webElementGuid>bee1ef78-2a0a-4729-8950-800969d29cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I play Dragonstone Battleground?'])[1]/following::div[9]</value>
      <webElementGuid>1efba6da-9e43-4a5e-bddf-cbf923251abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Fastfire?'])[1]/preceding::div[1]</value>
      <webElementGuid>7ae48879-f333-434b-8ea7-73e13a027622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>52c87dad-5cc6-4323-9d4e-03dc8e6abacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                     Fastfire 
                    ' or . = ' 
                     Fastfire 
                    ')]</value>
      <webElementGuid>cc48566d-e20b-461e-8168-a95094e3b48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
