<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gameplay</name>
   <tag></tag>
   <elementGuidId>f80c093e-8acf-4ad0-9075-ac002009bc8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-269d5bab']/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb11aa37-b62f-4cbd-b9a6-5973c770ff09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>a4dd9257-03a8-4fbe-81a6-3eb09fe9841d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                     Gameplay 
                    </value>
      <webElementGuid>57d75d9a-6312-42d5-9859-b7600cc77d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-269d5bab&quot;)/div[@class=&quot;faqs-listing&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;faq-category-box&quot;]/div[@class=&quot;heading&quot;]</value>
      <webElementGuid>823f5fcb-bc97-4238-96ba-09a16b40d0f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-269d5bab']/div/div/div[2]/div/div</value>
      <webElementGuid>ebe78b03-e6d8-417a-8cf6-3178be95a04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is MaxQuest legal?'])[1]/following::div[5]</value>
      <webElementGuid>f49e4035-d8d1-47aa-b9bd-a1b45a10d2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refer Friends page'])[1]/following::div[7]</value>
      <webElementGuid>ea7d8436-0fcd-4904-bf90-3bb7157a5b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who are the Heroes?'])[1]/preceding::div[1]</value>
      <webElementGuid>85e94300-b0cd-4415-b286-1e18007256c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>be92849c-68aa-4005-9e75-64552a467339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                     Gameplay 
                    ' or . = ' 
                     Gameplay 
                    ')]</value>
      <webElementGuid>ae180e1f-5687-4841-8024-43b516e910b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
