<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Battleground</name>
   <tag></tag>
   <elementGuidId>91c1aebf-a6be-48a7-8685-d6a486dfa239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-269d5bab']/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a68379d1-3f81-491e-9337-1f81df21f165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>d01ec41a-62b0-4ace-8a7c-68b39837e907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                     Battleground 
                    </value>
      <webElementGuid>65ed5e84-25f8-41d5-a56d-d7742f4eb8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-269d5bab&quot;)/div[@class=&quot;faqs-listing&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;faq-category-box&quot;]/div[@class=&quot;heading&quot;]</value>
      <webElementGuid>4bd2de32-9814-48fe-938e-8c597b943da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-269d5bab']/div/div[2]/div/div/div</value>
      <webElementGuid>5988e64f-c961-4822-8acf-27e1080249a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can I play Casino games at MaxQuest?'])[1]/following::div[6]</value>
      <webElementGuid>16027b39-c89d-443a-8a5f-259af500fb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are Worlds?'])[1]/following::div[10]</value>
      <webElementGuid>7f0139ef-1cfa-4998-aa2f-0affb211a252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is Battleground?'])[1]/preceding::div[1]</value>
      <webElementGuid>b6329298-4e02-4312-b870-286388f8c279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>82ebdeb3-41f3-48e4-b523-73cf2f89b7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
                     Battleground 
                    ' or . = ' 
                     Battleground 
                    ')]</value>
      <webElementGuid>c28b8b74-65a3-4d1c-8d21-e13fcc942734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
