<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Are there fees for deposits and withdrawa_a212a0</name>
   <tag></tag>
   <elementGuidId>2de94c9e-1adc-4e00-be0d-7721047b86eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordiondeposits-withdrawals']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle.data-faq-1954 > i.fas.fa-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bdfc5f9c-3635-465a-b76d-6a7554e84703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-chevron-down</value>
      <webElementGuid>c72cb443-6391-42ac-ac78-46c5f7d66e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordiondeposits-withdrawals&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/a[@class=&quot;accordion-toggle data-faq-1954&quot;]/i[@class=&quot;fas fa-chevron-down&quot;]</value>
      <webElementGuid>14c8f9ab-59e5-4e55-b8cc-7d645cad8a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordiondeposits-withdrawals']/div/div/a/i</value>
      <webElementGuid>7441aac5-d639-4a5a-b0fb-26c8b02fae62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div/div/a/i</value>
      <webElementGuid>9669af9e-63a3-441e-bf46-d4bd69a59bd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
