<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Can I change my personal information_fas _44b7ee</name>
   <tag></tag>
   <elementGuidId>64da567a-d80e-4de5-be61-3d3aa2706e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordionaccount']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle.data-faq-1940 > i.fas.fa-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fd79252a-e043-4d8d-a4e6-eea0b42cc5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-chevron-down</value>
      <webElementGuid>c1c6d1c0-1aae-4f23-b85f-9d4242e84bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionaccount&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/a[@class=&quot;accordion-toggle data-faq-1940&quot;]/i[@class=&quot;fas fa-chevron-down&quot;]</value>
      <webElementGuid>8d4d4193-ff43-4589-bf4c-ae219256a4cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionaccount']/div/div/a/i</value>
      <webElementGuid>e3c5ee02-a6e6-4831-9a64-2320542a0207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/a/i</value>
      <webElementGuid>be994887-8156-4d13-a6f1-b4e1a0083f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
