<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_What is Battleground_fas fa-chevron-down</name>
   <tag></tag>
   <elementGuidId>9bea00a6-4577-4e80-9d99-5cb3a1fcdbbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordionbattleground']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.accordion-toggle.data-faq-1930 > i.fas.fa-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2419c4da-52af-4398-9ddd-868de9939a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-chevron-down</value>
      <webElementGuid>0fc07dac-50a3-4d17-93fb-5793f253bfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionbattleground&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/a[@class=&quot;accordion-toggle data-faq-1930&quot;]/i[@class=&quot;fas fa-chevron-down&quot;]</value>
      <webElementGuid>dbc42df5-0f30-462c-b8b3-68c3157c1829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordionbattleground']/div/div/a/i</value>
      <webElementGuid>675fe9a5-8d5a-49e5-89a9-ba6571a8fc58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/a/i</value>
      <webElementGuid>a11ec3af-e2d3-4730-ac20-a41db2fdc1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
