<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact Customer Support to edit infor_e872d1</name>
   <tag></tag>
   <elementGuidId>3573c6de-9bbf-4461-b6de-01c4b27fd87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse-1940633c272bcd001']/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse-1940633c272bcd001 > div.panel-body > p > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>193249d2-31b0-4c4b-a3cb-6bb3fae605b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sheets-value</name>
      <type>Main</type>
      <value>{&quot;1&quot;:2,&quot;2&quot;:&quot;Contact Customer Support to edit information such as your name and phone number.&quot;}</value>
      <webElementGuid>2ea575f4-1f50-4e4f-94fe-68c8ca906594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sheets-userformat</name>
      <type>Main</type>
      <value>{&quot;2&quot;:7043,&quot;3&quot;:{&quot;1&quot;:0},&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:13228792},&quot;10&quot;:2,&quot;11&quot;:4,&quot;12&quot;:0,&quot;14&quot;:{&quot;1&quot;:3,&quot;3&quot;:1},&quot;15&quot;:&quot;Arial&quot;}</value>
      <webElementGuid>65fdd39f-0f34-4e5d-8d16-93399e0eae96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Customer Support to edit information such as your name and phone number.</value>
      <webElementGuid>4f5826f6-9871-4a42-8dc3-1c996dd44ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse-1940633c272bcd001&quot;)/div[@class=&quot;panel-body&quot;]/p[1]/span[1]</value>
      <webElementGuid>881c4f3d-e02e-446c-9f83-1b1f031a1679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-1940633c272bcd001']/div/p/span</value>
      <webElementGuid>352faaf6-42d2-407f-9ae2-12891a0bd251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Can I change my personal information?'])[1]/following::span[1]</value>
      <webElementGuid>f6b14fe2-06cd-4892-8afa-af6bdb7e9922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::span[1]</value>
      <webElementGuid>45bba540-bfda-4379-b62b-a8ef25787b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I change my password?'])[1]/preceding::span[1]</value>
      <webElementGuid>6a52dbe5-2c74-4e5c-aeaa-a52d4991487f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How old do I need to be to have a MaxQuest account?'])[1]/preceding::span[1]</value>
      <webElementGuid>a1e10635-a144-452b-a1b7-4f0bb4239d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Customer Support to edit information such as your name and phone number.']/parent::*</value>
      <webElementGuid>d15900f5-cfdc-46ee-bf6b-0f34afcb4890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/p/span</value>
      <webElementGuid>467fc1b4-d538-498d-a409-186ede6bc206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contact Customer Support to edit information such as your name and phone number.' or . = 'Contact Customer Support to edit information such as your name and phone number.')]</value>
      <webElementGuid>c638c2f8-c567-449f-a276-864ae2e19734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
