<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Max Rewards_vce-col-content</name>
   <tag></tag>
   <elementGuidId>266ea773-18b4-4b3a-ac0a-11f9b16de2b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-d48cc51e']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vce-col-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3c9f1be-53ac-492f-bdc8-1a43b6a9003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-col-content</value>
      <webElementGuid>3fc22f85-83bc-460e-b54a-2b6a38944221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vce-element-content</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>caec0694-76d4-478a-9392-1cc8c9f69998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vce-do-apply</name>
      <type>Main</type>
      <value>padding el-d48cc51e</value>
      <webElementGuid>1d25b5e0-746d-4ad1-8d29-05647828f45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-d48cc51e&quot;)/div[@class=&quot;vce-col-inner&quot;]/div[@class=&quot;vce-col-content&quot;]</value>
      <webElementGuid>26286ed5-2a4a-43bc-94d3-bcfe1f212a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60822214-a20f-480c-b639-f9bde481784a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vce-col-content</value>
      <webElementGuid>f99e9e98-179c-4a3f-bae9-68a21c71686d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vce-element-content</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a34f43c-0b32-43f5-9e0b-80319f4c173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vce-do-apply</name>
      <type>Main</type>
      <value>padding el-d48cc51e</value>
      <webElementGuid>1ca557f1-fa2d-448f-a3f9-3598f128309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-d48cc51e&quot;)/div[@class=&quot;vce-col-inner&quot;]/div[@class=&quot;vce-col-content&quot;]</value>
      <webElementGuid>bb0d0f30-f83c-4329-ac41-1faa1d037bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-d48cc51e']/div/div[2]</value>
      <webElementGuid>9e2754b0-3dbb-4b46-b5f5-d12c03a0f73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max Rewards'])[2]/following::div[24]</value>
      <webElementGuid>25e0aab8-c12b-4b4b-86e2-16dd9e1ca848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/following::div[29]</value>
      <webElementGuid>4aec9e14-5a4b-47b6-b280-82d155dc3791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFER FRIENDS AND GET REWARDED'])[1]/preceding::div[5]</value>
      <webElementGuid>befef386-7fb3-4c33-9ffe-7ea20473e677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get'])[1]/preceding::div[5]</value>
      <webElementGuid>dc16f418-fbbb-4707-ae1a-abf45ce12f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>c3149b45-2d4a-4214-9577-e3fc3dad07fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
