<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Samuel Keeler</name>
   <tag></tag>
   <elementGuidId>474f8a07-96f0-4dd8-a8f9-2cd3293fd4b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-855']/div/div[3]/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.user-info > h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>dcb6e439-eaa5-4523-b6ea-b8e5bb56cdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>0b3b3723-2466-45e6-a3b7-128bf433d426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>7592ae57-5615-4d63-af59-2f20b888a8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>85503944-45b5-47aa-ab17-cf2ad1f01dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>8dc22701-875a-46ba-aec4-25e0f9c77a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>3a1b2ef0-3bf0-481e-a1bd-fc093ad49858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>48365262-66cf-41c3-942e-bdf2e65f9d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>1436d3bd-aa6f-4979-a265-a5ce7e1672fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>c8353ead-555d-4d0c-8d66-2c0bc01c570b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>d8783396-a0a7-45cb-9403-963b5813dd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>cbe3a6c1-55df-4e56-90d6-fbaf61cfd020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>f656ff05-4326-45d8-8db6-db8ae236edc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>6b4c821f-e59a-445e-97a0-f1703b6b2509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>e4ce63a5-e1ec-4c1b-b4df-ea1e0de723f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>250f999f-e497-4c66-8c05-c3c4456a2eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f13af06a-e15e-483b-938c-bfce07efc036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>0346e077-ab85-476d-a973-fe5c80883629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>6e1f65f9-f9c4-432c-8e01-5222354e2e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1ebe3e5b-99b9-494f-b766-51cba4d45583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>114d659f-027b-4e67-8036-41955db323bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>b8884695-aa14-4220-be57-985887bdaa2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0e3e0fcf-89f8-4936-bf93-f62f13d0e515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>bf493e3a-b6d1-4347-9cd0-e14067492fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>84c4f3a5-afa3-44ff-a4eb-f79fd4dcd4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0b6ff391-6ee1-4603-9e9b-01408e78a7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>66e0c8dd-13eb-4f7a-b9c1-a58753770d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>51a108d6-fc84-49ad-92e8-e97c9b632b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>8802fee6-eb9f-44ee-afdb-4ac01bb710c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samuel Keeler</value>
      <webElementGuid>cae50fc8-aae3-48f0-8def-6ce0f3435faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/article[@id=&quot;post-855&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm col-sm-4&quot;]/div[@class=&quot;user-info-card&quot;]/div[@class=&quot;user-info&quot;]/h4[1]</value>
      <webElementGuid>bdd14967-81bd-4dde-abd1-751f0b0f0869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-855']/div/div[3]/div/div/h4</value>
      <webElementGuid>1be3a48a-abca-4b09-affe-735ae76401cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonus History'])[1]/following::h4[1]</value>
      <webElementGuid>2fe710d7-e2cd-447e-b36f-b8401c138f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[1]/following::h4[1]</value>
      <webElementGuid>f6eeeb9d-a610-4c46-bc93-e7ced2d2d6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SamKeeler'])[1]/preceding::h4[1]</value>
      <webElementGuid>61912d53-e2c0-45dc-9580-b261fd786911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Balance:'])[1]/preceding::h4[1]</value>
      <webElementGuid>ddddb3af-d43a-42d4-b25c-23dfc261c9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Samuel Keeler']/parent::*</value>
      <webElementGuid>63252b7d-dfc2-408a-9d14-b7496d04347d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h4</value>
      <webElementGuid>e83cd76e-99c2-4e1e-8b7f-9754b3559082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Samuel Keeler' or . = 'Samuel Keeler')]</value>
      <webElementGuid>20e51845-70c1-4888-9be6-aefe534ee7e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
